### ISSUE TITLE
High cpu usage in development ENV

### ISSUE THREAD

**Issue by pustovalov** [ai/size-limit#100]
I have updated the `size-limit` from `0.21` to `1.3.0` and after that size check for 15 files took:
```
✨  Done in 29.31s.
```

video: https://take.ms/wjy6D

example of `.size-limit.json`:
```
[
  {
    "path": "public/packs-test/common-*.js",
    "webpack": false,
    "limit": "15 KB"
  }
]
```

## Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Webpack           | 4.29.6     |
| Node             | 10.15.3    |
| Yarn         | 1.15.2     |
| Size Limit         | 1.3.0     |
| Operating System | macOS 10.14.4|

**Comment by ai** [comment]
It happens because we started to count JS compilation and execution time.

Tomorrow I will add one idea, which will speed up it few times.

Set `running: false` config to disable running time calculation and have old 0.x behavior.

**Comment by pustovalov** [comment]
Might be better to run one chromium for all files instead of unique chromium for each file?
<img width="400" alt="312312321331412421" src="https://user-images.githubusercontent.com/1568885/57030543-b8c96a00-6c4d-11e9-9165-5eb3f4f922ca.png">

**Comment by ai** [comment]
Good idea. I didn't think about the cases work multiple files.

@mbalabash can we add API for that?

**Comment by pustovalov** [comment]
With `running: false` it got better, `Done in 1.23s.`

**Comment by mbalabash** [comment]
Hello, guys
@ai Yes. I can do it in new version which uses `Tracium`.
Will try it today and let you know.

**Comment by ai** [comment]
Great. I will also replace throttling rate to `time / rate`. It is not accurate, but close enough.

**Comment by mbalabash** [comment]
> replace throttling rate to time / rate. It is not accurate, but close enough.

I agree.

**Comment by ai** [comment]
I improved performance https://github.com/ai/size-limit/commit/c1156e628727bd54a0f912fcf674e41c9a96f46e and released the fix in 1.3.1

I will keep the issue until @mbalabash will add multiple files support to `estimo` to improve performance even better.

**Comment by mbalabash** [comment]
I added multiple files support to new version.
But it not ready yet to release. 
@ai I give you update when it will be ready.

API looks like:
```sh
estimo -l react.production.min.js react.development.js
```
```js 
const report = await estimo(['react.production.min.js', 'react.development.js'])
```
```js
[ 
  { 
    library: 'react.production.min.js',
    parseHTML: 1.79,
    styleLayout: 59.6,
    paintCompositeRender: 1.07,
    scriptParseCompile: 1.2,
    scriptEvaluation: 9.03,
    javaScript: 10.23,
    garbageCollection: 0,
    other: 18.38,
    total: 93.31 
  },
  { 
    library: 'react.development.js',
    parseHTML: 1.17,
    styleLayout: 0.53,
    paintCompositeRender: 0.78,
    scriptParseCompile: 0.46,
    scriptEvaluation: 10.63,
    javaScript: 11.09,
    garbageCollection: 0,
    other: 15.7,
    total: 27.62 
  } 
]
```

**Comment by ai** [comment]
API looks great.

I will try to use it tomorrow.

**Comment by pustovalov** [comment]
`1.3.1`, without `running: false`:
```
✨  Done in 34.73s.
```

**Comment by mbalabash** [comment]
@pustovalov 
It because problem is how `estimo` counts JS compilation and execution time (each file in own Chrome).

New version very close. I think we can do upgrade in few days.
In new version all files will be process in one Chrome instance. 

Plus, we use new parser. Which works faster and give us more accurate results.

We will provide update here.

**Comment by pustovalov** [comment]
@mbalabash thx

**Comment by ai** [comment]
Size Limit 2.0 was released with modular architecture. Now (depends on preset) only necessary parts will be downloaded.
