### ISSUE TITLE
Reporting: configurable reporter format

### ISSUE THREAD

**Issue by grachpower** [ai/size-limit#101]
# 🚀Feature request
### Description
Now we can not select any output format.

### Alternatives you've considered
Provide any size-limit configuration with reporter type such as `html`, `plain`, `json`, etc.
```
+ "size-limit": [
+   {
+     ...
+     "path": "dist/app-*.js",
+     "reporter": "json"
+   }
+ ],
```

### Benefits
Customers like me can use any external build loggers to manage build statics

**Comment by ai** [comment]
I think it is better to specify format in CLI call:

```json
"scripts: {
  "test": "jest && size-limit --json"
}
```

It could be useful to have different output formats for different cases:

```js
"scripts: {
  "ci:test": "jest -i && size-limit --json",
  "test": "jest && size-limit"
}
```

But you can change my minds by use cases, where the format in config could be more useful.

**Comment by grachpower** [comment]
CLI json output looks good, thanks! it'l be helpful description in readme

**Comment by ai** [comment]
Yeap. Can you send PR to docs?
