### ISSUE TITLE
Exclude files from 

### ISSUE THREAD

**Issue by gupta2205** [ai/size-limit#103]
🚀Feature request
Description
Exclude/ignore bundle from path

It can be like 

```js
"size-limit": [
    {
      "webpack": false,
      "path": "dist/js/*.js",
      "exclude": "dist/js/native-*.js"
    }
  ],
```

Benefits
some bundles are only loaded on specific platform, those can be excluded.

**Comment by ai** [comment]
Try:

```js
"size-limit": [
    {
      "webpack": false,
      "path": [
        "dist/js/*.js",
        "!dist/js/native-*.js"
       ]
    }
  ],
```

If it will work, I will update docs to make this syntax more clear.

**Comment by ai** [comment]
I improved docs. b136bd8

Hope it will make `!pattern` easy to discover.
