### ISSUE TITLE
Unable to run size-limit on circle-ci

### ISSUE THREAD

**Issue by unional** [ai/size-limit#105]
I'm not sure if this is circle-ci issue or size-limit issue. But creating this just in case other people also encountered this:

https://circleci.com/gh/unional/unpartial/61?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link

```sh
> unpartial@0.0.0-development size /home/circleci/project
> size-limit

Failed to launch chrome! 
/home/circleci/project/node_modules/puppeteer/.local-chromium/linux-650583/chrome-linux/chrome: error while loading shared libraries: libXtst.so.6: cannot open shared object file: No such file or directory 
 
 
TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md 
 
Error: Can't execute 'npx /home/circleci/project/node_modules/.bin/perf-timeline'
Args: ["generate","file:///home/circleci/project/node_modules/estimo/temp/XXgClVWwQECctNuOWwG5B.html","--path","/home/circleci/project/node_modules/estimo/temp/5lhMr7k-r0CvJOqYpSsmu.json"]
    at ChildProcess.proc.on (/home/circleci/project/node_modules/estimo/src/perfTimelineCliAdapter.js:12:18)
    at ChildProcess.emit (events.js:193:13)
    at maybeClose (internal/child_process.js:999:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:266:5)
```

**Comment by unional** [comment]
It is about configuration:
https://discuss.circleci.com/t/puppeteer-fails-on-circleci/22650

**Comment by unional** [comment]
```sh
> unpartial@0.0.0-development size /home/circleci/project
> size-limit


 ERROR  WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.entry should be one of these:
   function | object { <key>: non-empty string | [non-empty string] } | non-empty string | [non-empty string]
   -> The entry point(s) of the compilation.
   Details:
    * configuration.entry should be an instance of function
      -> A Function returning an entry object, an entry string, an entry array or a promise to these things.
    * configuration.entry should be an object.
      -> Multiple entry bundles are created. The key is the chunk name. The value can be a string or an array.
    * configuration.entry should be a string.
      -> An entry point without name. The string is resolved to a module which is loaded upon startup.
    * configuration.entry should not be empty.
    at webpack (/home/circleci/project/node_modules/webpack/lib/webpack.js:31:9)
    at /home/circleci/project/node_modules/size-limit/index.js:119:20
    at new Promise (<anonymous>)
    at runWebpack (/home/circleci/project/node_modules/size-limit/index.js:118:10)
    at getSize (/home/circleci/project/node_modules/size-limit/index.js:236:25)
    at /home/circleci/project/node_modules/size-limit/cli-body.js:436:22
    at Array.map (<anonymous>)
    at main (/home/circleci/project/node_modules/size-limit/cli-body.js:406:34)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
```

**Comment by unional** [comment]
Seems like I can't find a way to see the flags `‘–no-sandbox’ ‘–disable-setuid-sandbox’` to `puppeteer.launch()` from `size-limit`.

Reopening.

**Comment by ai** [comment]
I added issue to estimo https://github.com/mbalabash/estimo/issues/6

**Comment by ai** [comment]
Should we add a warning about using `circleci/node:latest-browsers`? Do we have an environment variable in Circle CI with Docker image name?

We call show warning on Circle environment variable on error during estimo call.

**Comment by unional** [comment]
> Should we add a warning about using `circleci/node:latest-browsers`?

I think we should. The default `circleci/node:<version>` does not work.

> Do we have an environment variable in Circle CI with Docker image name?

Does not see that in https://circleci.com/docs/2.0/env-vars/#built-in-environment-variables

**Comment by unional** [comment]
Um... the webpack config error https://github.com/ai/size-limit/issues/105#issuecomment-491568357
also occurs locally on another repo.

I have set the config to
```
  "size-limit": [
    {
      "limit": "10kb"
    }
  ],
```

**Comment by ai** [comment]
I added warning 1218a85

Does `circleci/node:latest-browsers` help (at least it helped me on my Circle CI project) or we need to wait estimo to add arguments for Puppeteer call?

**Comment by unional** [comment]
Trying to figure out the webpack error.
It seems like the webpack config is cached somewhere?

Somehow in `unpartial` I can use the setting:
```
  "size-limit": [
    {
      "limit": "10kb"
    }
  ],
```
and it is working fine, but in another project, I have to use
```
  "size-limit": [
    {
      "limit": "10kb",
      "path": "lib/index.js"
    }
  ]
```

Since it is working in `unpartial` locally, I assume `size-limit` can get the default path from the `main` field. Is this the case?

**Comment by unional** [comment]
https://circleci.com/gh/unional/unpartial/84?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link

The `path: 'lib/index.js'` does not work correctly in circleci it seems. The relative path is not right.

**Comment by ai** [comment]
> It seems like the webpack config is cached somewhere?

Nope. Circle CI doesn’t have any caches if you explicitly doesn’t make them

**Comment by ai** [comment]
> Since it is working in unpartial locally, I assume size-limit can get the default path from the main field. Is this the case?

Default `path` is `package.main` or `./index.js`

**Comment by unional** [comment]
Um... cannot figure out why the webpack error occurs.
Do you mind take a look at it?
The repo is here: https://github.com/unional/type-plus/tree/size-limit

**Comment by ai** [comment]
> Um... cannot figure out why the webpack error occurs.

Did you run build script to generate `lib/index.js` before calling Size Limit? There is no `lib/index.js` in the project, only `src/index.js`.

**Comment by unional** [comment]
Yes I did. Correction. The issue locally is because the `main` field needs to be `lib/index.js`.

I originally have `lib/index` and that's when it fails locally.

However, it is still failing in circle-ci.
https://circleci.com/gh/unional/type-plus/475

**Comment by unional** [comment]
> I originally have `lib/index` and that's when it fails locally.

There was a recommendation to do this instead and let NodeJS resolves the right file, whether it is index.js, index.node or index.mjs.

**Comment by unional** [comment]
For the webpack error, if there is a way to log the resulting webpack config, we can see what happened.

**Comment by ai** [comment]
> For the webpack error, if there is a way to log the resulting webpack config, we can see what happened.

Locally you can put `console.log(config)` [here](https://github.com/ai/size-limit/blob/master/index.js#L236)

**Comment by unional** [comment]
For the extension issue, it is because of this: https://github.com/ai/size-limit/blob/master/cli-body.js#L344

It uses `globby` and not NodeJS resolve mechanism to resolve the file, so `main: "lib/index"` does not work.

Will see if I can debug in CI.

**Comment by unional** [comment]
Turns you the CI one is a stupid error. LIke you said, need to run `npm run build` first.
I didn't do that in that job.

So this issue can be closed.
The build is passing, even without  ‘–no-sandbox’ ‘–disable-setuid-sandbox’

Do you want me to open a separate issue for the extension problem?

**Comment by ai** [comment]
> Do you want me to open a separate issue for the extension problem?

Yeap. We need at least a warning (or maybe some extra code to auto-add extension)

**Comment by unional** [comment]
Will do. Thanks for all your help and your great tool~ 🌷

**Comment by ai** [comment]
Thanks for the issue. It helps us add useful warning
