### ISSUE TITLE
Handles packages with no file extension in the main field

### ISSUE THREAD

**Issue by unional** [ai/size-limit#106]
It is recommended to leave the extension off in the `package.json/main` field and let NodeJS resolves the right file whether it is `index.js`, `index.node`, `index.cjs`, or `index.mjs`

`size-limit` does not work with this format.

It uses `globby` instead of `NodeJS native resolution here:
https://github.com/ai/size-limit/blob/0a7ae6edaa8ab461c09dff099e09a2ce792679ff/cli-body.js#L339-L344

**Comment by ai** [comment]
Yeap, we do not need to use `globby` for `package.pkg.main`. Can I ask you to send PR to save your name in the project history?

**Comment by unional** [comment]
Sure. In that code, in what cases do you expect the `files` will be an array of more than one entry?

**Comment by ai** [comment]
`files` could be an array if it does from config. So `entry.path` should still use `globby`

**Comment by unional** [comment]
Seems like your tests uses `spawn()` to start `cli.js`. I want to print out some logs to see why tests is failing.
What's your prefer way to debug?
