### ISSUE TITLE
Automated dependency updates

### ISSUE THREAD

**Issue by pustovalov** [ai/size-limit#109]
What do you think about activate Dependabot for this repo?

https://dependabot.com/

Example: https://github.com/pustovalov/size-limit/pulls

**Comment by ai** [comment]
What will it give me?

**Comment by pustovalov** [comment]
Keep your dependencies up-to-date and see which update can break the library

**Comment by ai** [comment]
@pustovalov it is a description, but it is not a *my* benefits.

Right now I update dependencies manually on every release. How adding this tool will change my life?
