### ISSUE TITLE
Extract checks into plugins

### ISSUE THREAD

**Issue by timocov** [ai/size-limit#110]
First of all, `size-limit` is awesome, thank you!

But installing `size-limit` adds a lot of packages and downloads puppeteer+chromium, even if you don't use `webpack` or `running` option to run puppeteer.

Did you consider an option to split `size-limit` into several packages (plugins) - core checks, webpack-based checks, puppeteer-based checks and so on?

**Comment by ai** [comment]
There are 2 plans right now:

1. Allow using installed Chrome instead of downloading Puppeteer https://github.com/mbalabash/estimo/issues/7
2. Move time calculation to `time-budget` package.

Will plan 1 fix the problem for you?

**Comment by timocov** [comment]
Not only just a plan 1, but with a plan 2 it looks like it should be pretty good (if I understood correctly).

I add a little bit more context: our project is bundled by rollup, and total deps count is ~1.1k (700 dev deps and 400 for e2e tests purposes), but adding `size-limit` installs additional ~500 deps (almost 50% of already installed deps) (including a `webpack`, which is huge) and downloads Chromium.

We don't want to bundle our code by webpack again (as soon we bundle it by rollup already), we just want to check a size and compare it with out limits (to prevent significant size increasing).

Also, adding checking of execution time can add more false positive results because this check hasn't a stable result (after some testing this feature I've got a different results for every run for the same file) and it can be a bottleneck for CI/DX.

But if we'll have a tiny `time-budget` package with a minimal count of deps, which will check only size of file - it would be awesome.

> and CI times is not a big deal

I don't really agree with you in this - if we can decrease CI time, we should do this. There is a difference if a developer will wait (for example) 1 minute for the whole pipeline or 5 minutes (just to respect a developer time and reduce usage of CI services). But this isn't a subject for this issue 🙂

**Comment by ai** [comment]
OK, good idea. I will think how to do split project into 2 projects on next week.

**Comment by timocov** [comment]
Hey @ai, any updates on this? Possible do you need help with that?

**Comment by ai** [comment]
No changes. Right now I am spending my free time for Logux docs.

It will be hard to help because we need to start a new project and make a lot of architecture changes.

**Comment by ai** [comment]
Size Limit 2.0 was released with modular architecture. Now (depends on preset) only necessary parts will be downloaded.

**Comment by timocov** [comment]
Thank you!
