### ISSUE TITLE
Add custom import

### ISSUE THREAD

**Issue by ai** [ai/size-limit#111]
```js
  import: "import { List } from 'lib'"
```

https://twitter.com/brian_d_vaughn/status/1133378518820069376

**Comment by theKashey** [comment]
Was just going to create the same issue - `scenario-based size measurements`.
Like I am going to use the library like `this` - what would be the impact.

**Comment by theKashey** [comment]
Not promising anything, but I need this feature so maybe.
Do you have API in mind?
I could see two different posibilities:

- simple. Just specify imports. Ie `import default, {List} from "dist/es2015/index.js";`
```js
  {
    path: "dist/es2015/index.js",
    imports: ['default', 'List'], // import "this" from "that"
    limit: "4 KB"
  },
```
- complex (but very interesting) - use `npm pack` to pack the package, and use it as a package, so all endpoints and all `imports` would be 100% real.
```js
  {
    scenario: "
      import { List } from 'myLib";
      import { Tree } from 'myLib/endpoint';
    ",
    limit: "4 KB"
  },
```

**Comment by theKashey** [comment]
It would make `size-limit` a bit slower, as long as `npm pack` might trigger `build`

**Comment by theKashey** [comment]
if you want to `import from 'XXX'`, especially `XXX/yyy` - you have to pack and unpack your stuff. However, we might use webpack alias to bound 'XXX' to the current dir.

**Comment by theKashey** [comment]
😅

**Comment by ai** [comment]
@bvaughn @theKashey we have a solution to test the library size with tree-shaking.

Thanks to @bschlenk. We will release it when we will finish docs,

https://github.com/ai/size-limit/pull/166

**Comment by ai** [comment]
The current API:

```js
  "size-limit": [
    {
      "path": ".",
      "import": "a, b",
      "limit": "15 KB"
    }
  ]
```

Which will create a test:

```js
import { a, b } from "."
console.log(a, b)
```

**Comment by bschlenk** [comment]
I just realized that if `import` takes a string then there isn't really a way to specify the default export. From https://github.com/ai/size-limit/issues/111#issuecomment-525556388, if `import` took an array then we can special case `default` to mean the default export. Although, could a module do `export const default = 'someting'`, in which case they'd never be able to test that one?

I'm leaning more towards the scenario suggestion above with `npm pack`. I'd have to rework my PR though. With the `import` as array api, I don't know if it would really be testing tree shaking. I wanted this feature to make sure that I included `sideEffects: false` in my package.json. I'd expect different imports without that flag to yield the same size.

**Comment by ai** [comment]
@bschlenk what if we change the syntax to:

```js
    "import": "{ methodA, methodB }"
```

or 

```js
    "import": "defaultExport, { methodA, methodB }"
```

**Comment by bschlenk** [comment]
I like that, it simplifies the code around handling the default import. But does it leave too much room for error? `default` is a reserved word, so if someone wrote `"import": "default"` it would cause the script to fail. Does it make sense to add sophisticated validation around this to detect issues early?

**Comment by ai** [comment]
We can add denylist with popular mistakes like `default`.

But, to be honest, I think people will use library name here like:

```js
import: "React, { Component }"
```

We definitely need to check that string do not start from `import ` because people may start to put the whole import statement there.

**Comment by bvaughn** [comment]
Cool! I'll be happy to use it.

**Comment by theKashey** [comment]
Ideally `size-limit` also should check that all imported stuff exists. Not really your business, but there is always a room for a typo - imagine `import: "React, { component }"`

**Comment by ai** [comment]
Lens start without check and add it later. I afraid checking could be hard.

**Comment by theKashey** [comment]
Well, there is a way to make it simpler - add an option(where?) to have that generated file as `.ts`. You will simultaneously check that everything you asked for exists and that types are properly defined for the entrypoint.
That would not work for everyone, but it's really one line change and some part of us would be very grateful for it.

**Comment by ai** [comment]
`import` option was added at 4.1 release

**Comment by theKashey** [comment]
Just in time.
