### ISSUE TITLE
New option --no-sandbox

### ISSUE THREAD

**Issue by igorkamyshev** [ai/size-limit#113]
Hello! Great lib, thanks for that.

I suggest new option '--no-sandbox'. It option must be passed to puppeteer. It is important. If I want run size-limit in GitHub Action, it will be executed as root and broke down, because puppeteer require '--no-sandbox' option, when it executed by root user.

What do you think? I can make a PR, if you agreed add this option.

**Comment by ai** [comment]
Maybe we should ask [estimo](https://github.com/mbalabash/estimo) to always use this option?

/cc @mbalabash

**Comment by ai** [comment]
I created an issue https://github.com/mbalabash/estimo/issues/8

**Comment by igorkamyshev** [comment]
Thanks! 🤓

**Comment by mxstbr** [comment]
The change in estimo was shipped, any chance we can use this with size-limit? :pray:

**Comment by ai** [comment]
@mxstbr we are waiting for this issue https://github.com/mbalabash/estimo/issues/9

**Comment by ai** [comment]
1.3.8 uses Estimo 1.1, which will use local desktop Chrome

**Comment by ai** [comment]
Size Limit 2.0 was released with modular architecture. Now (depends on preset) only necessary parts will be downloaded.
