### ISSUE TITLE
`estimo` importing `puppeteer` and headless chrome (80MB)

### ISSUE THREAD

**Issue by toomuchdesign** [ai/size-limit#118]
Hi!
First of all thanks for this extremely useful tool!

I just updated `size-limit` in a project of mine, and I was a little bit disoriented seeing this little library downloading `puppeteer` and a whole **80MB** instance of **headless chrome** in my `node_modules` folder! 😄

I see that this **banana-gorilla-jungle** thing is coming from `estimo`, probably to evaluate the execution time. Is there any plan or possibility to see this huge chunk of dependencies **not being included by default**?

I'm using `size-limit` as a size security check for [react-minimal-pie-chart](https://github.com/toomuchdesign/react-minimal-pie-chart) and I feel we might also benefit from taking care of the health of the dev side of our JS ecosystem.

Thanks again for your awesome work here. Happy to contribute or to follow the discussion if it makes sense.

Cheers! ✌️

**Comment by ai** [comment]
Hi. Thanks for warm words.

Here is an issue to use Chrome from the system instead of download it https://github.com/mbalabash/estimo/issues/7

I recently pinged @mbalabash

Will this idea work for you?

**Comment by toomuchdesign** [comment]
Hi! mbalabash/estimo#7 looks promising.

I don't get what would happen on a CI environment lacking a local Chrome instance, though.
Forcing CI to download/install an additional 80MB on each `git push` might be also overkill.

Another non-exciting solution might consist of splitting the library into something like `size-limit` and `size-limit-e2e`. 🙈

.. or -better- skipping the `Chrome`-related checks when Chrome is not available?

**Comment by mbalabash** [comment]
@toomuchdesign 
It's a good point.
Right now, on CI, puppeteer + chrome just cached in your build system as npm dependencies.
But with script for downloading chrome as not part of npm it can be really expensive (

**Comment by ai** [comment]
Yeap, I have a idea to split Size Limit to Size Limit and Time Budget.

**Comment by timocov** [comment]
It looks like it's related to #110

**Comment by ai** [comment]
1.3.8 uses Estimo 1.1, which will use local desktop Chrome
