### ISSUE TITLE
CLI configuration options are not working

### ISSUE THREAD

**Issue by theKashey** [ai/size-limit#119]
- `--no-gzip` has no effect. Test - reported size should change.
  - it does support `--gzip=false`, but expect `false` to be a boolean
- `--no-webpack` has no effect. Test - `--why` should throw
  - it does support `--webpack=false`, but expect `false` to be a boolean

**Comment by ai** [comment]
Can you try `--no-gzip` on master?

I fixed 52459cf

**Comment by ai** [comment]
I tried `--no-webpack` and seems like works. Maybe I test in different way.

**Comment by ai** [comment]
Can you test `master` that issue was fixed and `-no-webpack` works?

If everything OK I sill release your changes and this fix.

**Comment by theKashey** [comment]
`-no-webpack` works 👍

**Comment by ai** [comment]
Released in 1.3.7
