### ISSUE TITLE
Prefer npx

### ISSUE THREAD

**Issue by theKashey** [ai/size-limit#120]
Since `puppeteer` has been shipped within `size-limit` the _size-limit_ of subj become a bit bigger than the nice level.

Personally, I am looking forward to removing `size-limit` from `devDependencies` and use it via `npx`, as long as it allows me to have only one installation per machine.

While it would affect size-limit metrics - that's probably better for a customer for now, until yarn-pnp/tick would change the game rules.

**Comment by ai** [comment]
I have other option to split a project into `size-limit` and `time-budget`.

I am closing it as duplicate since using `npx` will not solve the problem

https://github.com/ai/size-limit/issues/118#issuecomment-500199771

**Comment by theKashey** [comment]
#118 sounds interesting.
