### ISSUE TITLE
Post comments on PRs

### ISSUE THREAD

**Issue by mxstbr** [ai/size-limit#124]
It would be awesome if `size-limit` didn't just fail CI, but also commented on every PR with the new sizes and download times of the app to create better awareness of the limits.

**Comment by ai** [comment]
I afraid that making this UI will make the system much more complicated. Half of bundlesize issues in 1.0 plan related with GitHub comment integration.

My main concern is that we do not have the same UX for tests and linters.

I agree that it will improve UX. But I think about it only after splitting project into `size-limit` and `time-budget` (to keep JS running time calculation in separated projects only for teams who will have `5s` like limits).

However, it is not a final word and I am open for arguments.

**Comment by mxstbr** [comment]
I think there could easily be a GitHub app that wraps size-limit! I don't think that would require any changes to this package and I think would also not be dependent on any CI environment variables, i.e. solves most of the issues that bundlesize is encountering with that feature.

**Comment by ai** [comment]
Yeap. It is solvable. Just not in number 1 priority since time budget will have more effect to the community.

I think even for most of big React libraries JS compilation and execution time is much more important and understandable number than abstract bytes (bytes forces us to compare JS size with images size which is not correct due to the difference processing time).

**Comment by krzkaczor** [comment]
@ai @mxstbr it's actually very simple to turn this (awesome 😍 ) package into a plugin to [codechecks.io](https://codechecks.io/) platform and integrate with PR flow. Codechecks offloads all complicated things like communication with GitHub, storing artifacts etc. from the developer and exposes simple JavaScript (TypeScript) API 💪 

Some time ago I wrote a very simple implementation of bundle size tracking here: https://github.com/codechecks/build-size-watcher but turning `size-limit` into a fully fledged codecheck would be amazing!

We have all the documentation here: https://github.com/codechecks/docs and I can help you if you have any other questions.

**Comment by ai** [comment]
@krzkaczor wow, thanks for the advice.

I will look into the project after returning from Atacama dessert.

**Comment by ai** [comment]
Yeap. We definitely need something like this.

But first I will try to open my OpenCollect and try to get paid time for Size Limit by https://opencollective.com/chrome

I just do not have too many projects. This month all my free time goes to [Logux docs](https://github.com/logux/logux).

**Comment by krzkaczor** [comment]
@ai I totally get what you mean, time is a scarce resource 😢 

I will see if I will find some time to work on this over the weekend 👍 There's an API so it should be relatively simple to create a proper codecheck.

**Comment by krzkaczor** [comment]
I added initial implementation here: https://github.com/ai/size-limit/pull/127 

You can see it in action on this PR: https://github.com/krzkaczor/cc-prod-playground/pull/5

@ai @mxstbr would you like to test it further?

**Comment by andresz1** [comment]
Hi,

I just created [size-limit-action](https://github.com/marketplace/actions/size-limit-action) a GitHub action that post comments on PRs with the comparison of Size Limit output. It could also reject a PR if the cost exceeds the limit. I took some ideas from your comments and also from @krzkaczor PR.

If you have time, let me know what you think! any feedback or idea will be more than welcome.

Thanks in advance @mxstbr @ai @krzkaczor

**Comment by ai** [comment]
@andresz1 wow, I love it 😍

Can you send PR to `README.md` with extra Reports section with a guide and screenshot? (Just to save your name in the project’s history).

What is your Twitter name to mention you in the tweet about your project?

**Comment by andresz1** [comment]
Thanks @ai I'm really glad you like it!

Sure! like the one is in the action ? Let me know if I can help in something else 😉
My twitter name is: @andresz_s

**Comment by ai** [comment]
> Sure! like the one is in the action?

Yeap. Just to improve your Action discoverability.

**Comment by andresz1** [comment]
Just opened the PR #169. Let me know what you think!
