### ISSUE TITLE
Migration guide for v2?

### ISSUE THREAD

**Issue by dpikt** [ai/size-limit#133]
Hi, are there any docs about migrating from v1 to v2? Want to make sure I don't break anything :)

**Comment by ai** [comment]
We are showing docs on `npx size-limit` call. Just install a preset and remove `size-limit` from dependencies.

**Comment by ai** [comment]
Maybe we can add the note to `CHANGELOG.md`. Do you want to send PR?

**Comment by dpikt** [comment]
@ai done!
