### ISSUE TITLE
Migration to v2 with npx

### ISSUE THREAD

**Issue by ahtohbi4** [ai/size-limit#135]
I am using `size-limit@1` by `npx` without the installation of it with other `devDependencies`.

I have tried to migrate on v2:

 1. updated NPM-scripts

```diff
- "check-size": "npm run buld && npx size-limit@1"
+ "check-size": "npm run buld && npx size-limit@2"
```

2. installed a preset according to docs to the projects `devDependencies`

```bash
$ npm i -D @size-limit/preset-big-lib
```

3. tried to launch script

```bash
$ npm run check-size
```

and have got the error

```
Error: Cannot find module '@size-limit/preset-big-lib'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:655:15)
    at Function.Module._load (internal/modules/cjs/loader.js:580:25)
    at Module.require (internal/modules/cjs/loader.js:711:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at toArray.concat.filter.reduce (/Users/aantonov/.npm/_npx/4022/lib/node_modules/size-limit/load-plugins.js:11:36)
    at Array.reduce (<anonymous>)
    at loadPlugins (/Users/aantonov/.npm/_npx/4022/lib/node_modules/size-limit/load-plugins.js:11:6)
    at module.exports (/Users/aantonov/.npm/_npx/4022/lib/node_modules/size-limit/run.js:26:19)
```

Is it means that in this case, `size-limit` tries to find the preset in global `node_modules`? And is it possible to avoid this error?

**Comment by ai** [comment]
Can you replace `npx size-limit@2` to `npx size-limit`?

`npx` should go into local `node_modules` and find `size-limit` there. You have a `size-limit` in `node_modules` because it is dependency of `@size-limit/preset-big-lib`. Maybe because of the different `npx` call it uses global `size-limit` instead.

**Comment by ai** [comment]
Maybe we should use smarter `require` here to be sure of using local `node_modules` https://github.com/ai/size-limit/blob/master/packages/size-limit/load-plugins.js#L11

Do you want to send PR?

**Comment by ahtohbi4** [comment]
> Can you replace npx size-limit@2 to npx size-limit?

You are right! I pointed to the v2 to be sure to use it, but this version was already provided by the preset.

Thanks! My problem was solved. 👍

**Comment by ahtohbi4** [comment]
> Maybe we should use smarter require here to be sure of using local node_modules https://github.com/ai/size-limit/blob/master/packages/size-limit/load-plugins.js#L11
>
> Do you want to send PR?

I'd wish but I don't sure that I can to test it before creating PR. :sweat_smile:

**Comment by ai** [comment]
You don’t need to have tests in that PR
