### ISSUE TITLE
"size-limit" badge and github checks

### ISSUE THREAD

**Issue by artalar** [ai/size-limit#136]
Hi!
Mooving to reducing the size of the web is great, thx for this lib.

How can we accentuate libs with that mooving? Maybe "size-limited" badge will a good label that indicates the intention to lower the size of a library.

I propose 2 things:
1) Create [badge](https://shields.io/) especially for size-limit (simple task)
2) Create Github-app, that integrates with the library repo and run checks on each PR (harder tsk). I know that I can write my custom GitHub Actions for run size-limit check, but it will be cool if that functionality will be able simple as PnP.

**Comment by ai** [comment]
I like the idea of promotion. But I think the different method will be better:

* Badges works badly. They have very small unreadable text. There are a lot of unnecessary badges in practice. As a result, visitors ignore badges.
* I found that small text in the project description is better. Check out [nanoid](https://github.com/ai/nanoid/) docs.

**Comment by ai** [comment]
I added suggestion to add size to docs https://github.com/ai/size-limit/commit/8b9ceed833af11514809a73075f6465b781e2ce6
