### ISSUE TITLE
Simultaneous updates of dependencies

### ISSUE THREAD

**Issue by avdeev** [ai/size-limit#138]
Hi, @ai! Thank you for the good tool!

I noticed that after the division of the library to the core and presets they increase their versions together. It is not so convenient for supporting. On each size-limit release I need to upgrade two dependencies instead of one.

![image](https://user-images.githubusercontent.com/1241671/64412343-dbeea500-d097-11e9-8da9-6aedabd158a7.png)

Are there any plans to fix this? Or is it some kind of concept?

**Comment by ai** [comment]
Try to remove `size-limit` from `dependencies`. Anyway preset had it in own dependencies.

**Comment by avdeev** [comment]
Thank you! it's genius :)

**Comment by ai** [comment]
I will reopen it to make warning to prevent future issues like this

**Comment by ai** [comment]
I added warning 2120383

**Comment by ai** [comment]
Released in 2.1.4

**Comment by avdeev** [comment]
@ai Hi!
The situation with a simultaneous update of dependencies is reproduced again

**Comment by ai** [comment]
What solution do you suggest?
