### ISSUE TITLE
--why not working in many normal situations

### ISSUE THREAD

**Issue by Offirmo** [ai/size-limit#140]
The `--why` option is working, albeit not in some nominal situation:

1) if the quota is exceeded (the very reason I want to use `--why`), the command force-exits with `error Command failed with exit code 1.` due to the quota being exceeded, killing the web server on the way...

2) if several limitations are passed, for ex. one for ESM and one for CJS, the command attempts to launch 2x web servers, resulting in "EADDRINUSE" error, causing the command to force-exits, killing the web server on the way...

I believe those problems are unwanted, especially #1

For now, I had to alter my config to avoid both cases #1 and #2

**Comment by ai** [comment]
I will try to fix it this week. If you like you can send PR to `packages/webpack/index.js` and `packages/size-limit`.

**Comment by Offirmo** [comment]
Thanks. I have no time at the moment to do it myself, I mainly wanted to let you know. No hurry, I had it working by solving the 2 points.

**Comment by ai** [comment]
Problem 1 was fixed 34b8180

**Comment by ai** [comment]
Problem 2 was fixed too 0787d0f

**Comment by ai** [comment]
Released in 2.1.6

**Comment by Offirmo** [comment]
Tested with 2.1.6, I'm confirming 1 and 2 are fixed. @ai you are awesome!
