### ISSUE TITLE
--why flag not showing any info

### ISSUE THREAD

**Issue by samayo** [ai/size-limit#142]
I just discovered this library today, it's very nice. 

But I have an issue with `--why` flag. It doesn't show the cost if the test fails (i.e size exceeds beyond the limit specified)

This issue might be related to #140 

### setup

```
 "devDependencies": {
  ...
  "@size-limit/preset-app": "2.1.6",
  "@size-limit/webpack": "2.1.6",
  ...
 },
 script": {
  "size": "size-limit",
 }
```

If I run `npm run size --why` I just get the limit has exceeded output and not why.

I am not sure if there is some additional config I have forgotten, as #140 is fixed 2.1.6

**Comment by ai** [comment]
`--why` works only with npm packages with multiple files inside.

`--why` doesn’t work if you have own webpack. In this case, just install Webpack Bundle Analyzer manually and use Size Limit only for the budget.

Also, you need to remove `@size-limit/webpack`. It is incompatible with `@size-limit/preset-app`. Seems like you install this plugin because you were confused by `--why` error text. How I can change error text to prevent future users from installing `@size-limit/webpack` in the future?

**Comment by samayo** [comment]
Sorry, I just realized I forgot an important part of the code: 

```
  "size-limit": [
    {
      "path": "compiled/js/vendor.js",
      "webpack": false,
      "running": false,
      "limit": "2.25 mb"
    },
    {
      "path": "compiled/js/app.js",
      "webpack": false,
      "running": false,
      "limit": "200 kb"
    }
  ],
``` 

This is in `package.json` along with the previous code

**Comment by ai** [comment]
Use `@size-limit/file` if you do not want to have Running time calculation.

>  the issue is only with the flag

What is expected behavior for `--why` in the cases when it can’t work?

**Comment by samayo** [comment]
Sorry for my English bro. I simply want to see the visualized data as shown in the readme
when I run the size command with `--why`. If I don't include the flag, I can see clearly the expected/actual file size, so size-limit is working well. If I include `--why` however I don't see this image: 



![image](https://user-images.githubusercontent.com/5304093/65885869-a047b200-e39b-11e9-967f-c5e634b3c3c7.png)

That's what I was trying to say.

**Comment by ai** [comment]
You can’t see this image if you use your own webpack. `--why` works only with `@size-limit/preset-small-lib` or `@size-limit/preset-big-lib`.

You need to use Webpack Bundle Analyzer in your webpack config.

**Comment by samayo** [comment]
thanks
