### ISSUE TITLE
Improve documentation for JS API

### ISSUE THREAD

**Issue by the-clx** [ai/size-limit#148]
Hi.

I tried to use JS API but current documentation doesn't help.

**Comment by ai** [comment]
What tasks you can’t solve with the current JS API?

**Comment by the-clx** [comment]
Even example from readme doesn't work for me. I created repo with reproduced issue https://github.com/the-clx/size-limit-not-array. Could you check why it's crashing?

**Comment by the-clx** [comment]
I realized I need webpack plugin even use test file not even bundled. Why the file plugin is not working alone?

**Comment by ai** [comment]
It should work for one file. Maybe we need some fixes in the code. I am working on this task and will give a fix in a day.

**Comment by the-clx** [comment]
Thanks

**Comment by ai** [comment]
Fixed 89b4114

**Comment by ai** [comment]
Released in 2.2.2.

Open new issue if you will need some extra docs.
