### ISSUE TITLE
Supporting custom webpack.config.js

### ISSUE THREAD

**Issue by indexzero** [ai/size-limit#16]
Interested in using your project, but the projects in which we would be using it do not build using the webpack config included in `index.js`. 

Would you be interested in a PR that allows for a custom webpack config file path to be provided? 

e.g. 
```
size-limit --config ./webpack.config.js
```

The `webpack.config.js` file would be expected to:

- Export a single `webpack` config object
- Not include any compression or minification plugins

... thoughts?

**Comment by ai** [comment]
Sure. Let's do it. Do you want to make PR?

Also, why custom config should not include compression and minification plugins? What if users will want to customize them too?

**Comment by indexzero** [comment]
Totally possible. I was assuming that the `Compression` and `Uglify` plugins the `webpack` config in `index.js` uses were intentional. e.g. what would happen if one attempted to use `require('webpack').optimize.UglifyJsPlugin` instead of  `require('uglifyjs-webpack-plugin')`?

**Comment by ai** [comment]
`uglifyjs-webpack-plugin` loads latest beta with ES6 support

**Comment by indexzero** [comment]
Got it. What I'm trying to figure out is the best way to (or if it's feasible) to implement the following:

- Is it possible to determine if an arbitrary webpack config object, `config`, needs modification by `size-limit`? 

In other words: what's an efficient way to check if `config.plugins` has both a compatible minifier plugin and a compatible compression plugin?

**Comment by ai** [comment]
I think we could ignore this problem. If you pass custom config, it is your responsibility now.

If we will have a lot of issues, we can add check later.

**Comment by indexzero** [comment]
That's reasonable. Will take a stab at this in the next couple of weeks.

**Comment by SivanMehta** [comment]
@indexzero @ai I have submitted #29 to enable a `--config` flag that supports a custom webpack config.

**Comment by ai** [comment]
Released in 0.12

**Comment by oliviertassinari** [comment]
@SivanMehta I'm wondering, how are you using this --config option? How do you handle the `files` option?
https://github.com/ai/size-limit/blob/22860808c9066e18f64aee87764eb6da4ed36b8a/index.js#L32-L49

**Comment by SivanMehta** [comment]
This PR should have supported the usage as described in the initial issue descriptions

```
size-limit --config ./my-custom-webpack.config.js
```
