### ISSUE TITLE
Failing on CI with "Error: Invalid task timing data"

### ISSUE THREAD

**Issue by larsenwork** [ai/size-limit#160]
Not sure if it's a bug in this package or with the CI but maybe 20% of the time it fails with:

```bash
#!/bin/bash -eo pipefail
yarn size:check
yarn run v1.21.1
$ size-limit
Error: Invalid task timing data
    at Function.getMainThreadTasks (/home/circleci/project/node_modules/tracium/lib/main-thread-tasks.js:259:15)
    at Function.compute (/home/circleci/project/node_modules/tracium/lib/main-thread-tasks.js:272:28)
    at Object.computeMainThreadTasks (/home/circleci/project/node_modules/tracium/index.js:13:36)
    at generateTasksReport (/home/circleci/project/node_modules/estimo/src/reporter.js:6:18)
    at async generatePrettyReport (/home/circleci/project/node_modules/estimo/src/reporter.js:25:19)
    at async estimoJsMode (/home/circleci/project/node_modules/estimo/src/js-mode/index.js:14:21)
    at async estimo (/home/circleci/project/node_modules/estimo/src/lib.js:38:32)
    at async getTime (/home/circleci/project/node_modules/@size-limit/time/get-running-time.js:18:14)
    at async Promise.all (index 3)
    at async sum (/home/circleci/project/node_modules/@size-limit/time/index.js:8:11)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Exited with code exit status 1
CircleCI received exit code 1
```

It runs on an `circleci/node:12-browsers` image and in package.json it's just 
```json
  "scripts": {
	"size:check": "size-limit",
  },
  "size-limit": [
    {
      "path": "build/static/js/*.js",
      "limit": "12 s"
    }
  ],
```

Let me know if there is more I can do to debug/test or if you need more info. 

— Thanks

**Comment by robinvdvleuten** [comment]
I run into the same issue on CircleCI; sometimes it works, sometimes it don't.

**Comment by ai** [comment]
@mbalabash do you know why it could happen?

**Comment by mbalabash** [comment]
@ai 
Seems like [tracium](https://github.com/aslushnikov/tracium) failed during parsing Chromium trace events.

@robinvdvleuten , @larsenwork Did it work well until on the 11 of February 2020?

**Comment by mbalabash** [comment]
I opened an issue in [tracium](https://github.com/aslushnikov/tracium/issues/15).

**Comment by robinvdvleuten** [comment]
@mbalabash I have the issue on CircleCI since I've started using this library somewhere in January 2020.

**Comment by larsenwork** [comment]
We only started using size-limit recently but I'm fairly certain we've also had the issue before the 4th of February 2020.

**Comment by mbalabash** [comment]
Thanks for your answers. 

I thought that it happened after new Chrome version. But if you had this issue before then it probably another issue with puppeteer on CI. 

Hope that `tracium` team will provide more information about causes behind this error.

**Comment by pustovalov** [comment]
started getting this error after updating from:
```
Chrome 79.0.3945.130
ChromeDriver 79.0.3945.36
```

to:
```
Chrome 80.0.3987.106
ChromeDriver 80.0.3987.106
```

**Comment by larsenwork** [comment]
Just a thought — it might be related to this when seeing @pustovalov comment: 
https://www.reddit.com/r/webdev/comments/f26mbn/chrome_80_introduces_a_new_bug/

**Comment by mbalabash** [comment]
@larsenwork I'm not sure. But with Chrome 79 I couldn't reproduce this error.

@ai I released `estimo:2.0.2` ([changelog](https://github.com/mbalabash/estimo/blob/master/CHANGELOG.md)) with temporary fix in `findChrome` script. Now it won't use chrome with version >= 80.

**Comment by mbalabash** [comment]
I did more than 10 tests on CI and more than 50 on my local machine. It was worked without this error.

I hope it could be a solution for now.

**Comment by vrizo** [comment]
Also, you can enforce node executor to use `circleci/node:12.12-browsers`. There is chrome-80 in `node:12-browsers`, and and 77 in `node:12.12`.

For example:

_.circleci/config.yml_

```yml
executors:
  node-executor:
    docker:
      - image: circleci/node:12.12-browsers
```

**Comment by ai** [comment]
@mbalabash thanks for your time.

I think we do not need special `@size-limit/time` release since I used `^` version query there.
