### ISSUE TITLE
Add a way to test tree-shaking size

### ISSUE THREAD

**Issue by bschlenk** [ai/size-limit#161]
This may be out of scope for this project, but it would be really cool to be able to test out tree-shaking benefits with this tool. If there was a way to configure a file and an export to pull from that file, it could be a great way to make sure tree shaking is set up properly.

**Comment by ai** [comment]
We can add `import` directive to the config like:

```json
  "size-limit": [
    "import": "import { method } from '.'",
    "limit": "15 KB"
  ]
```

Will, it fit your task?

Do you want to send PR?

**Comment by bschlenk** [comment]
Yeah, that would be really cool! I'll take a look at it this weekend and see if I can get you a PR.

**Comment by bschlenk** [comment]
I started looking into this, but wanted your advice on the best way to implement. In order for this to work, it would have to write a new file to use as the webpack `entry` file. Where would be the best place to write this file? In the temp directory that gets created [here](https://github.com/ai/size-limit/blob/master/packages/webpack/index.js#L47)?

**Comment by ai** [comment]
> Where would be the best place to write this file? In the temp directory that gets created here?

Yeap, it is a good candidate for this temp file

**Comment by bschlenk** [comment]
This is harder than I thought. If I create a file with just `import { method } from '.'`, webpack treeshakes everything out because `method` is never called. The config could be required to use the import as well, like `import { method } from '.'; method()`, but that doesn't feel right. Any thoughts?

**Comment by ai** [comment]
Another idea:

Config:

```js
  "size-limit": [
    {
      "path": ".",
      "import": "a, b",
      "limit": "15 KB"
    }
  ]
```

In `entry` file you put:

```js
import { IMPORT } from "PATH"
console.log(IMPORT)
```

So, in this case, you will have:

```js
import { a, b } from "."
console.log(a, b)
```

**Comment by bschlenk** [comment]
Didn't see there was already a similar issue. Should I close this in favor of https://github.com/ai/size-limit/issues/111 ?

**Comment by ai** [comment]
Yeap, let’s close this one
