### ISSUE TITLE
Running only on first CI job

### ISSUE THREAD

**Issue by abaicus** [ai/size-limit#165]
Hello,

Size limit won't run on GitHub actions because of the [`ci-job-number`](https://github.com/ai/ci-job-number/blob/master/index.js#L27) dependency. 

The issue here is that we have no control over the order the CI jobs are running. 

For example on the job I run this inside, `GITHUB_RUN_NUMBER` is equal to 9.

You can see this happening here: https://github.com/Codeinwp/neve/runs/460206357?check_suite_focus=true#step:8:4

Is there a workaround for this? Am I not using GitHub Actions properly?

Thanks in advance! 👍

**Comment by ai** [comment]
I will revert that changes at `ci-job-number`

**Comment by ai** [comment]
I added the environment variable to override the default behavior for the future 4b18169

**Comment by ai** [comment]
Let’s use `CI_JOB_NUMBER` override for now.

https://github.com/ai/ci-job-number#override-default-behaviour

I released it in `ci-job-number` 1.2.1. Will it work for you?

I afraid that current GitHub Actions behaviour is still work for most of use cases. You have edge case and hack solution is normal in this case.

**Comment by abaicus** [comment]
@ai Thanks! Surely the override will work fine for this. I also used a hacky solution as a quick fix:

```
      - name: Install Dependencies
        run: npm install
      - run: npm run build
      # WORKAROUND FOR SIZE-LIMIT
      - run: |
          GITHUB_RUN_NUMBER_TMP=GITHUB_RUN_NUMBER && export GITHUB_RUN_NUMBER=1;
          echo "$GITHUB_RUN_NUMBER"
          npm run-script size
          export GITHUB_RUN_NUMBER=GITHUB_RUN_NUMBER_TMP
          echo "$GITHUB_RUN_NUMBER"
```

 The `CI_JOB_NUMER` env var will do great and declutter the workflow.

Thank you! :+1:

**Comment by madou** [comment]
hi i'm actually running into this as well. are we sure this isn't more of a wide spread issue?

https://github.com/atlassian-labs/compiled-css-in-js/runs/594915180

![image](https://user-images.githubusercontent.com/6801309/79614866-d0428100-8144-11ea-96b1-83f26c452a90.png)

**Comment by ai** [comment]
@madou can yu send PR and remove GitHub from `ci-job-number`?

**Comment by madou** [comment]
sure

**Comment by madou** [comment]
https://github.com/ai/ci-job-number/pull/19

**Comment by ai** [comment]
Done. We removed GitHub Actions in `ci-job-number 1.2.2`. Update your lock files.
