### ISSUE TITLE
Question: Example image

### ISSUE THREAD

**Issue by EmptyStackExn** [ai/size-limit#168]
Hello, I really appreciate the design of the [example image](https://github.com/ai/size-limit/blob/master/img/example.png). May I know the operating system and terminal emulator that was used for it ? Thanks.

**Comment by ai** [comment]
I like issues like this 😊

GNOME Terminal on Linux with Adwaita theme (the standard terminal and theme on Fedora).

**Comment by EmptyStackExn** [comment]
Thanks! And what is the font you're using ?

**Comment by ai** [comment]
Fira Code

**Comment by EmptyStackExn** [comment]
Love it! And how do you manage to take a screenshot with the light shadow below the window ?

**Comment by ai** [comment]
It is a default GNOME Screenshot app. It has a shadow effect.
