### ISSUE TITLE
[Yarn 2] EROFS: read-only filesystem, mkdir '/node_modules/@size-limit/.cache'

### ISSUE THREAD

**Issue by insanecoding** [ai/size-limit#173]
Hi and thanks for the awesome tool!

I'm now trying `size-limit` + `@size-limit/preset-big-lib` with Yarn 2 and I have a problem.

I have `size` script defined in this way: `"size": "yarn clean && yarn build && size-limit",`

When I execute `yarn size`, it gives me the following error log:

<img width="637" alt="Screenshot 2020-03-31 at 16 15 54" src="https://user-images.githubusercontent.com/3858809/78036712-e7bef300-736a-11ea-947e-47c1b9b6b7fb.png">

The problem is that the `time` plugin is trying to write into read-only directory which is prohibited by ZipFS that Yarn 2 uses.

The line which is causing the problem:

https://github.com/ai/size-limit/blob/60dfdc9a55228c60f5e715d4cdbf615e047b2430/packages/time/cache.js#L10

**Comment by ai** [comment]
I am thinking of setting `true` to [`unplugged`](https://next.yarnpkg.com/configuration/manifest#dependenciesMeta.unplugged) flag for `@size-limit/time`.

But maybe you know a better place for a cache? Should we add an environment variables to change cache path?

**Comment by ai** [comment]
Another way is to disable cache for Yarn 2

**Comment by insanecoding** [comment]
so this addition to `package.json` solved my problem:
```json
  "dependenciesMeta": {
    "@size-limit/time": {
      "unplugged": true
    }
  }
```

maybe that's enough and we don't need to do any path-related changes. it can be tricky because of different environments (linux/unix and windows). they have different paths to `temp` directory and `cross-env` should be used for reliable env variable setup

**Comment by ai** [comment]
Try 4.4.4 release without `dependenciesMeta`. I added the flag directly to `@size-limit/time`.
