### ISSUE TITLE
Feature proposal:  extend default webpack configuration

### ISSUE THREAD

**Issue by toomuchdesign** [ai/size-limit#175]
Hi @ai,
I was wondering whether the maintainers of this library have strong opinions against allowing users to **freely extend default webpack configuration** like, to mention one, [storybook does](https://storybook.js.org/docs/configurations/custom-webpack-config/).

It could consist of single call to a user-provided function that mutates or recreates webpack's config.

In my specific case, I wanted to add `babel-loader` to strip out `propTypes` declarations with [babel-plugin-transform-react-remove-prop-types](https://www.npmjs.com/package/babel-plugin-transform-react-remove-prop-types) shipped with the library under test, but I think this extra layer could come in handy in a lot of corner cases.

Glad to make a PR if interested.

Thank for your efforts, here. Cheers!
Andrea,

**Comment by ai** [comment]
Why `config` option is not a solution for you https://github.com/ai/size-limit#config

**Comment by toomuchdesign** [comment]
I'd like to fully rely on the default provided by the library in [`webpack/get-config.js`](https://github.com/ai/size-limit/blob/master/packages/webpack/get-config.js) and add something on top of it.

If I don't get it wrong, it might also back us up in case defaults settings get updated in future. 🤞

**Comment by ai** [comment]
Another way. Write a Size Limit plugin, which will runs after `@size-limit/webpack` and change its config. I can give you access to `@size-limit/` npm’s namespace or we can add custom plugins API to Size Limit.

**Comment by toomuchdesign** [comment]
Good point. A custom `size-limit` plugin should provide the necessary grip surface to expand the bundling configuration. Thank you so much!

Closing for now, I'll ping you back if I end up with something worth publishing.
Keep up the great work.
