### ISSUE TITLE
Minification before size check

### ISSUE THREAD

**Issue by erykpiast** [ai/size-limit#178]
What do you think about such an option? I can see it as one similar to `webpack` one. It could be just as simple as `terser` and than, when it's enabled, `config` would mean a Terser config.

I don't like such an API, to be honest, because you cannot really choose both Webpack and Terser at the same time (and as far as I can see, when you use default Webpack config, it's already minified), but well, it's quite an easy to implement non-breaking change.

**Comment by ai** [comment]
`@size-limit/webpack` alrady does minification before showing size.

Are you want to create a plugin just to call minifcation without webpack? What is your use case?

**Comment by erykpiast** [comment]
Yes, I wish to do exactly that. My use-case is `nanoutils` a set of tiny lodash-like utilities. There is a need to check the size of every single utility. See this comment: https://github.com/nanoutils/nanoutils/pull/208#issuecomment-620847840.

**Comment by ai** [comment]
For tools like this I suggest to use `import` key:

```
  "size-limit": [
    {
      path: "index.js",
      import: "{ sortBy }",
      limit: "500 ms"
    }
```

It will be much more accurate than checking file size (because of webpack inline functions from ESM)

**Comment by ai** [comment]
You can use the `import` option in JS API as well.

**Comment by Beraliv** [comment]
@ai 

`nanoutils` uses size.js

https://github.com/nanoutils/nanoutils/blob/529d9d2bc2e24e0daab5b84424a5db5854f394a8/misc/cli/size.js#L5

to compare two libraries

https://github.com/nanoutils/nanoutils/blob/529d9d2bc2e24e0daab5b84424a5db5854f394a8/misc/cli/size.js#L92

It will lead to the table

https://github.com/nanoutils/nanoutils/blob/master/SIZES.md

so do I understand write that instead of doing:

```js
let nanoutilsSumSizePromise = getSize(fixture('nanoutils/sum.js'))
let ramdaSumSizePromise = getSize(fixture('ramda/sum.js'))

const [nanoutilsSumSize, ramdaSumSize] = await Promise.all([nanoutilsSumSizePromise, ramdaSumSizePromise])
```

we should do something like:

```js
let nanoutilsSumSizePromise = getSize({
  path: [fixture('nanoutils/sum.js')],
  import: {
    [fixture('nanoutils/sum.js')]: 'sum'
  },
  gzip: true
})

let ramdaSumSizePromise = getSize({
  path: [fixture('ramda/sum.js')],
  import: {
    [fixture('ramda/sum.js')]: 'sum'
  },
  gzip: true
})

const [nanoutilsSumSize, ramdaSumSize] = await Promise.all([nanoutilsSumSizePromise, ramdaSumSizePromise])

// another code
```

Do I understand right?

**Comment by ai** [comment]
```js
import getSize from 'size-limit'
import webpackPlugin from '@size-limit/preset-small-lib'

async function getMethodSize (path, method) {
  const result = await getSize(webpackPlugin, {
    checks: [
      {
        path: [fixture(path)],
        import: `{ ${ method } }`
      }
    ]
  })
  return result.size
}


const [nanoutilsSumSize, ramdaSumSize] = await Promise.all([
  getMethodSize('nanoutils', 'sum'),
  getMethodSize('ramda', 'sum)
])
```

**Comment by erykpiast** [comment]
@ai In that setup is bundling made multiple times, once for each method?

**Comment by ai** [comment]
Yeap, you can improve performance by calling `getSize` once with multiple `checks` items.

**Comment by erykpiast** [comment]
Alright, thank you! So as the use-case is covered and you don't see a point in minifying code without bundling with Webpack, I suppose we can close the issue. Is that right?

**Comment by ai** [comment]
> you don't see a point in minifying code without bundling it with Webpack, I suppose we can close the issue.

Yeap, I think we should call Webpack to add all `require` and Node.js polyfills, which can dramatically change the result.
