### ISSUE TITLE
Stripping out non production code

### ISSUE THREAD

**Issue by eXon** [ai/size-limit#18]
Maybe this feature already exists and I am not aware but it would be great to be able to strip the non production code (NODE_ENV != "production" or anything like that). As an example, the React library is wildely using thing and it would be a shame to include invariant and stuff like that within the bundle size.

What do you think about that?

By the way, awesome plugin I love it

**Comment by ai** [comment]
It’s awesome, that you thought about it.

And we, of course, implemented it from first versions :D https://github.com/ai/size-limit/blob/master/test/index.test.js#L59-L63

**Comment by eXon** [comment]
Oh great sorry about that 👍
