### ISSUE TITLE
Remove React dependency in time package

### ISSUE THREAD

**Issue by dunklesToast** [ai/size-limit#182]
The [time](https://www.npmjs.com/package/@size-limit/time) package required React. As far as I could see it does not use it so thats kind of an unnecessary import.

If it's really not used, please remove to keep the node_modules folder small!

**Comment by ai** [comment]
I used React as a big JS file to benchmark the developer CPU.

Do you have an idea, what JS file I can use instead?

**Comment by dunklesToast** [comment]
Hmm. Not directly but if it's just for testing couldn't you just remove the dependency or move it to a devDependecy? The time package has ~10000 downloads a week so thats a lot of people downloading React without actually using it.

**Comment by ai** [comment]
It is not testing.

Size Limit needs a React source to benchmark your CPU and normalize your CPU power to get JS parsing time the same no matter of your CPU.

This is how `@size-limit/time` works:

1. Parse React sources on your machine.
2. Compare React parsing time to the time needed to old Snapdragon CPU. Get a slow down factor.
3. Cache steps 1-2.
4. Parse your sources with factor from step 2.

**Comment by ai** [comment]
Feel free to suggest an alternative to benchmark user’s CPU
