### ISSUE TITLE
Using size-limit with just `file` plugin doesn't output `gzipped` as note

### ISSUE THREAD

**Issue by timocov** [ai/size-limit#185]
It seems that there is no `gzip` plugin referenced in https://github.com/ai/size-limit/blob/3571e79736a5cd7bf9cf245ff7d5ea2e3ac5f9ef/packages/size-limit/create-reporter.js#L86-L87, isn't it? Just guess that in this check we need to have something like `plugins.has('file') && check.gzip !== false`?

**Comment by ai** [comment]
Yeap. It is a bug :D.

Do you want to send PR and save your name in the project’s history?

**Comment by timocov** [comment]
Yeah, sure #186.
