### ISSUE TITLE
Size-limit exits with non-zero if sizes are equal to reported

### ISSUE THREAD

**Issue by okonet** [ai/size-limit#19]
Steps to reproduce:

1. Create a config and run `size-limit` to see the report
1. Update the config with the _exact same number_ from the report
1. Run `size-limit` again and see it failing with

```
  Package has exceeded the size limit
  Package size: 1.8 KB
  Size limit:   1.8 KB
  With all dependencies, minified and gzipped
```

**Comment by ai** [comment]
Seems like we need to show bytes here to explain reason.

**Comment by ai** [comment]
But this issue will be low priority since we recommend to add extra bytes for limits. In you case, most of PR will fall build step. Even if you add one single variable.

**Comment by okonet** [comment]
Makes sense but still very confusing for the first experience. Probably some error boundaries should be backed into the library?

**Comment by ai** [comment]
Can’t reproduce :(. Can you share your project?

**Comment by okonet** [comment]
Been trying it here: https://github.com/okonet/attr-accept/pull/11 and ended up increasing the limit.

**Comment by ai** [comment]
Done c6e45a3

**Comment by ai** [comment]
I will release it with messages fixes.

**Comment by okonet** [comment]
Thanks!

I'm still a bit concerned about the DX here. Now it reports size in bytes, but we specify it in KBs or even MBs :trollface: which will lead to an additional mental overhead for developers. I see at least two ways how this can be improved:

1. Do not show the actual size, instead show the difference.
1. Additionally display pretty formatted sizes 

Something like:

```
Limit exceeded by 142 Bytes!
Actual size: 16343 B (1.6 KB)
Size Limit: 15634 B (1.6 KB)
```

**Comment by ai** [comment]
I like the idea to show the difference! :)
