### ISSUE TITLE
Optionally add reporting about lesser size

### ISSUE THREAD

**Issue by victordidenko** [ai/size-limit#202]
Now if size is exceeding limit, there is error message:
```
  build/index.js
  Package size limit has exceeded by 9 B
  Size limit: 360 B
  Size:       369 B with all dependencies, minified and gzipped
```

But there is no "hurray" message about lesser size, for example:
```
  build/index.js
  Package size is 5 B less than limit 🎉
  Size limit: 360 B
  Size:       355 B with all dependencies, minified and gzipped
```
(of course this should not cause error)

When I have many files to check against size-limit, and I'm doing some work to decrease library size, trying different approaches over and over, it is sometimes hard to see few bytes difference in `size-limit` report.

Maybe add command line option, or environment variable for that?

**Comment by ai** [comment]
Yeap. It will be nice to have extra option `size-limit --no-less`, which will render these cases in yellow.

Please send PR (sorry, I am spending my time on other open-source projects right now).

**Comment by victordidenko** [comment]
Ok, I'll try 👌

`--no-less` — you mean like warning, not encouraging?
Why not `--with-less` and show them in green?

**Comment by ai** [comment]
Hm. Yeap, we can make it more positive. `--highlight-less` and `greenBg`?

**Comment by victordidenko** [comment]
PR #203
