### ISSUE TITLE
Update to webpack v5

### ISSUE THREAD

**Issue by jaydenseric** [ai/size-limit#205]
We should be optimizing our packages for the most recent version of webpack, which is now v5.

Importantly, it understands the package `exports` field:

- https://nodejs.org/api/packages.html#packages_exports
- https://webpack.js.org/guides/package-exports

Also, [it doesn't automatically polyfill the Node.js `process` global for the browser](https://github.com/webpack/changelog-v5#automatic-nodejs-polyfills-removed). Right now, I'm trying to `size-limit` test a package containing React component code like this:

```js
// Allow the display name to be eliminated from production bundles.
if (typeof process === 'object' && process.env.NODE_ENV !== 'production')
  Foo.displayName = 'Foo';
```

Webpack v4 sees the `process` related code, and inserts a massive `./node_modules/process/browser.js` shim that can not be ignored by the `size-limit` config `ignore` option, because that shim is added by webpack and is not imported anywhere in the code I'm testing.

**Comment by ai** [comment]
Yeap. I like to migrate to webpack 5, but do not have time to do this, since spending all my time with Logux State.

Can you send PR?

**Comment by jaydenseric** [comment]
[Logux State](https://github.com/logux/state) 👀

Does only the `@size-limit/webpack` need work? It seems so running `npm ls webpack`:

```
├─┬ @size-limit/preset-small-lib@4.7.0
│ └─┬ @size-limit/webpack@4.7.0
│   ├─┬ css-loader@5.0.1
│   │ └── webpack@4.44.2 deduped
│   ├─┬ file-loader@6.2.0
│   │ └── webpack@4.44.2 deduped
│   ├─┬ optimize-css-assets-webpack-plugin@5.0.4
│   │ └── webpack@4.44.2 deduped
│   ├─┬ style-loader@2.0.0
│   │ └── webpack@4.44.2 deduped
│   └── webpack@4.44.2
```

**Comment by ai** [comment]
Yeap, only `@size-limit/webpack`
