### ISSUE TITLE
How to use this with frameworks built with webpack like create-react-app?

### ISSUE THREAD

**Issue by THPubs** [ai/size-limit#21]
I tried to use this library with a project built with create-react-app. There's no folder where they put the webpack bundle.js. So I tried to build the project and run size-limit on the resulting bundle. This gave the size of the bundle. But when I tried to see `why` it was unable to separate the packages. Just showed only the app bundle:

<img width="1678" alt="screen shot 2017-09-18 at 8 01 38 pm" src="https://user-images.githubusercontent.com/1212023/30547192-3cb67d8a-9cac-11e7-8ed3-e5181a9aa12f.png">

It would be great if you can add support for these special scripts too. 😃

**Comment by ai** [comment]
Is your project website or open source npm package?

**Comment by THPubs** [comment]
It's a web app. Not a package.

**Comment by ai** [comment]
In this case, it will be better to use [Webpack Bundle Analyzer](https://github.com/th0r/webpack-bundle-analyzer) inside your webpack.

In this case, `size-limit` will be just tool for Travis CI.

**Comment by THPubs** [comment]
Perfect thanks!
