### ISSUE TITLE
Failed to execute size-limit on Debian GNU/Linux 10 (buster)

### ISSUE THREAD

**Issue by smonusbonus** [ai/size-limit#212]
After upgrading to v4.9.2 our builds started failing with the following error message:

```
✔ Adding to empty webpack project
Running JS in headless Chrome
Error: Failed to launch the browser process!
node_modules/estimo/temp/chrome/linux-706915/chrome-linux/chrome: error while loading shared libraries: libXss.so.1: cannot open shared object file: No such file or directory

TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

at onClose (/var/lib/jenkins/jobs/productlist-renderer/branches/master/workspace/node_modules/puppeteer-core/lib/cjs/puppeteer/node/BrowserRunner.js:193:20)
at Interface.<anonymous> (/var/lib/jenkins/jobs/productlist-renderer/branches/master/workspace/node_modules/puppeteer-core/lib/cjs/puppeteer/node/BrowserRunner.js:183:68)
```

After manually installing libXss via apt-get the execution works again. Just want to understand why this is happening/necessary? Some interface for a screen saver tool seems somewhat unrelated to what size-limit is doing. 

Can someone help?

**Comment by ai** [comment]
This error happens because of headless Chrome for JS loading time limit calculation.

If you do not really care about making a limit in `ms` or `s`, I recommend switching to `KB` limits. Running headless Chrome is always hard.

**Comment by ai** [comment]
I changed docs to not forcing time-based limit for everyone https://github.com/ai/size-limit/commit/cf961287fd9b19d8fc259f5ee583d6f6bf3538a0
