### ISSUE TITLE
[Proposal] fall if entry not found

### ISSUE THREAD

**Issue by binjospookie** [ai/size-limit#213]
Hi!

I test `./<some-path>/someFileName.js` file with size-limit.

Path to file or file's name can be changed. If I don't change `.size-limit.json` I got a warning `File not found: ./<some-path>/someFileName.js`.

Maybe should add a flag like `--no-warnings` and exit size-limit with error code in this cases?

I can implement it if you're agree.

**Comment by ai** [comment]
I think we always should fail on missed entries. Can you send PR?

**Comment by binjospookie** [comment]
Yes
