### ISSUE TITLE
Size reported incorrectly due to usage of factor 1024

### ISSUE THREAD

**Issue by MatthiasKunnen** [ai/size-limit#218]
**What happens**  
When the size is `4632 bytes`, size-limit reports `4.52 KB`. However, this size is in `KiB`. This is due to the [bytes package not currently following](https://github.com/visionmedia/bytes.js/issues/26), and [not willing to follow](https://github.com/visionmedia/bytes.js/pull/36), [the standard set forth by ISO, BIPM, and IEC](https://en.wikipedia.org/wiki/Binary_prefix#Adoption_by_IEC,_NIST_and_ISO).

**What should happen**  
size-limit should follow the standard and report `4.63 KB`.

**Solution**  
Use a package like [pretty-bytes](https://www.npmjs.com/package/pretty-bytes) or [bytes-iec](https://www.npmjs.com/package/bytes-iec) which follows the standards and converts sizes properly.

**Comment by ai** [comment]
I like the idea of moving `KiB` units =^_^=

Can you send PR and change the text in the code? You can replace `bytes` with any library, which has 0 dependencies.

**Comment by ai** [comment]
Fix was released in 4.10.2
