### ISSUE TITLE
Improve NPX Support / Passing Config Options via CLI

### ISSUE THREAD

**Issue by Saeris** [ai/size-limit#23]
Hey I discovered both this project and `npx` today thanks to your blog-post introducing `size-limit`. One immediate drawback that stood out to me from the documentation and a cursory glance at the source code, and that was the lack of ability to pass config options via the CLI.

It would be nice if I could just run `npx size-limit -p "./src/index.js" --why` and thanks to the magic of `npx` I can quickly see how bloated my project is without having to modify my project in any way. I think going forward this would also be an excellent way to get people to try it out, just for how friction-less it is.

This would go along great with #16 as well. I recently tried running `size-limit` on a project written in typescript, and obviously that's not going to work out of the box, especially when the webpack config for the project wasn't in the root directory.

Thanks for putting this out there! I'd make a PR for this change, but as a front-end dev I'm not very familiar with the ins and outs of writing node.js CLI scripts.

**Comment by ai** [comment]
Good idea. Can you try this:

```sh
npx size-limit ./src/index.js --why
```

It should work right now.

**Comment by Saeris** [comment]
Received the following:

```shell
$ npx size-limit ./src/index.js --why
npx: installed 1 in 2.047s
Path must be a string. Received undefined
C:\Users\Saeris\AppData\Roaming\npm-cache\_npx\43864\node_modules\size-limit\cli.js
 ERROR  Size Limit can't resolve
        dns
        in D:\GitHub\Flickr-Wormhole\node_modules\isemail\lib
```

I haven't used `size-limit` on this project yet, so I don't think having run the command in that directory before would have anything to do with it, if that's a possible bug with `npx`.

**Comment by ai** [comment]
CLI API works fine. You have a different issue with `size-limit`.

Did you run `npm install`? Do you have `dns` in your project `dependencies`/`devDependencies`?

**Comment by Saeris** [comment]
I did install project dependencies via `yarn` instead of `npm install`.

I'm not using `dns` in my project as far as I'm aware, it's not in my project deps.

```json
"dependencies": {
    "apollo-server-hapi": "^1.1.2",
    "babel-polyfill": "^6.16.0",
    "babel-runtime": "^6.26.0",
    "dataloader": "^1.3.0",
    "date-fns": "^1.28.5",
    "good": "^7.3.0",
    "good-winston": "^4.0.0",
    "graphql": "^0.11.4",
    "graphql-custom-types": "^1.1.0",
    "graphql-iso-date": "^3.3.0",
    "graphql-relay": "^0.5.2",
    "graphql-tools": "^1.0.0",
    "hapi": "^16.6.2",
    "winston": "^2.3.1"
  },
  "devDependencies": {
    "aws-sdk": "^2.123.0",
    "babel-cli": "^6.16.0",
    "babel-core": "^6.26.0",
    "babel-eslint": "^8.0.1",
    "babel-loader": "^7.1.2",
    "babel-minify-webpack-plugin": "^0.2.0",
    "babel-plugin-lodash": "^3.2.11",
    "babel-plugin-transform-class-properties": "^6.24.1",
    "babel-plugin-transform-commonjs-es2015-modules": "^3.0.2",
    "babel-plugin-transform-decorators-legacy": "^1.3.4",
    "babel-plugin-transform-es2015-classes": "^6.24.1",
    "babel-plugin-transform-es2015-shorthand-properties": "^6.18.0",
    "babel-plugin-transform-function-bind": "^6.22.0",
    "babel-plugin-transform-imports": "^1.4.1",
    "babel-plugin-transform-object-rest-spread": "^6.26.0",
    "babel-plugin-transform-runtime": "^6.23.0",
    "babel-plugin-webpack-alias": "^2.1.2",
    "babel-preset-env": "^1.0.2",
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-flow": "^6.23.0",
    "babel-preset-react": "^6.24.1",
    "babel-preset-stage-0": "^6.24.1",
    "body-parser": "^1.15.2",
    "cors": "2.8.4",
    "dotenv": "^4.0.0",
    "env-cmd": "^7.0.0",
    "eslint": "^4.7.0",
    "eslint-import-resolver-webpack": "^0.8.3",
    "eslint-plugin-compat": "^1.0.4",
    "eslint-plugin-flowtype": "^2.36.0",
    "eslint-plugin-graphql": "^1.3.0",
    "eslint-plugin-import": "^2.7.0",
    "eslint-plugin-jest": "^21.2.0",
    "eslint-plugin-promise": "^3.5.0",
    "eslint-plugin-react": "^7.4.0",
    "flow": "^0.2.3",
    "flow-bin": "^0.55.0",
    "graphql-tag": "^2.4.2",
    "imports-loader": "^0.7.1",
    "isomorphic-fetch": "^2.2.1",
    "lint-staged": "^4.2.3",
    "lodash": "^4.17.4",
    "lodash-webpack-plugin": "^0.11.4",
    "prettier": "^1.7.0",
    "serverless-domain-manager": "^1.1.12",
    "serverless-offline": "^3.15.3",
    "serverless-webpack": "^3.1.0",
    "webpack": "^3.6.0",
    "webpack-node-externals": "^1.6.0"
  }
```

**Comment by Saeris** [comment]
For reference I'm running:

```
Windows 10
node: v8.5.0
yarn: 1.0.2
npm: 5.4.2
npx: 9.6.0
```

**Comment by ai** [comment]
Can you try add `size-limit` to config and run `npx size-limit` (just to find the source of the problem)?

Maybe this project is open sourced?

**Comment by Saeris** [comment]
Okay, one of my sub dependencies was `dns` and I was unaware of it. Here's the output:

```shell
$ npx size-limit --why
npx: installed 1 in 1.515s
Path must be a string. Received undefined
D:\GitHub\Flickr-Wormhole\node_modules\size-limit\cli.js
 ERROR  Size Limit can't resolve
        dns
        in D:\GitHub\Flickr-Wormhole\node_modules\isemail\lib
```

And here's the project if you want to take a look at it, I'm still working out some bugs so you may not be able to get it to run.

https://github.com/Saeris/Flickr-Wormhole

**Comment by ai** [comment]
Yeap, seems like `isemail` uses `dns` but doesn’t have it in `dependencies`.

Add `dns` to your dev dependencies: `npm install --save-dev dns`. Will it fix CLI?

**Comment by Saeris** [comment]
No dice

```shell
Saeris@Tristram MINGW64 /d/GitHub/Flickr-Wormhole (develop)
$ yarn add -D dns
yarn add v1.0.2
[1/5] Validating package.json...
[2/5] Resolving packages...
warning node-uuid@1.4.8: Use uuid module instead
[3/5] Fetching packages...
info fsevents@1.1.2: The platform "win32" is incompatible with this module.
info "fsevents@1.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
error hawk@0.10.2: The engine "node" is incompatible with this module. Expected version "0.8.x".
error Found incompatible module
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

Saeris@Tristram MINGW64 /d/GitHub/Flickr-Wormhole (develop)
$ npx size-limit --why
npx: installed 1 in 1.747s
Path must be a string. Received undefined
D:\GitHub\Flickr-Wormhole\node_modules\size-limit\cli.js
 ERROR  Size Limit can't resolve
        dns
        in D:\GitHub\Flickr-Wormhole\node_modules\isemail\lib
```

Looks like `dns` might not work in my environment. I might be able to do without the actual dependency that;s including it, `graphql-custom-types`, which I'm using to add custom GraphQL scalars to validate URLs and Email addresses, which I could just use String types instead. Most of the issues I'm dealing with in my project at the moment are GraphQL related.

**Comment by ai** [comment]
:( I will try to investigate it on this weekend.

**Comment by Saeris** [comment]
Sounds good! I should catch some sleep anyways it's almost 5am.

**Comment by jcrugzz** [comment]
`dns` is a node internal library that is being used that is unable to be resolved based on how this library works. I'm pretty sure this is because webpack is not able to polyfill node dependencies from those packages. I'd try and file a pull-request against isemail to make it more client-side friendly if that is the only thing blocking this.

**Comment by ai** [comment]
Yeap seems like it is `webpack` vs. `dns` problem.

You need to add:

```js
"browser": {
  "dns": false
}
```

to your project `package.json` to prevent webpack resolving module. We do the same in PostCSS: https://github.com/postcss/postcss/blob/master/package.json#L74
