### ISSUE TITLE
Can size-limit check node code?

### ISSUE THREAD

**Issue by akatechis** [ai/size-limit#235]
Along the lines of why it's important to have manageable size/time budgets for libraries and applications for browsers, does this package also support linting the "weight" of a node js library/application?

I'm particularly interested in size/time checks for a nodeJS library written in TS.

**Comment by ai** [comment]
You can do it. But I can recommend packagephobia.

Do you compile TS to JS before publishing to npm?

**Comment by akatechis** [comment]
> 
> You can do it. But I can recommend packagephobia.

Thanks, I will take a look at that.

> 
> Do you compile TS to JS before publishing to npm?

I do.

**Comment by ai** [comment]
You can install `@size-limit/file` and use `*.ts` in config `path` to track the size of source code.

But I think for Node.js libraries it is better to track `node_modules` footprint (including subdependencies)
