### ISSUE TITLE
Error while downloading chromium

### ISSUE THREAD

**Issue by olegKusov** [ai/size-limit#239]
npm install --save-dev @size-limit/preset-app
 
 Windows 11
 WSL 2

Downloading Chromium r884014...
Chromium downloaded to /home/oleg/.../node_modules/estimo/temp/chrome/linux-884014
Downloaded Chrome executable path: /home/.../node_modules/estimo/temp/chrome/linux-884014/chrome-linux/chrome
/home/oleg/.../node_modules/estimo/temp/chrome/linux-884014/chrome-linux/chrome: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory
ERROR: Failed to download Chromium r884014!
Error: Command failed: "/home/oleg/.../node_modules/estimo/temp/chrome/linux-884014/chrome-linux/chrome" --version
/home/oleg/.../node_modules/estimo/temp/chrome/linux-884014/chrome-linux/chrome: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory

**Comment by ai** [comment]
If you do not need JS execution time, you can avoid `@size-limit/time` plugin (for instance, by replacing `@size-limit/preset-app` to `@size-limit/file`).

If you need it, open an issue in `estimo`.
