### ISSUE TITLE
Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.

### ISSUE THREAD

**Issue by hhimanshu** [ai/size-limit#241]
# Bug report

**What is the current behavior?**
The `npx size-limit` command fails with the following error
```
➜  ts-react-components-lib git:(hhimanshu/update-deps) ✗ npx size-limit
✖ Adding to empty webpack project
 ERROR  WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.entry['index'] should be an non-empty array.
   -> A non-empty array of non-empty strings
    at webpack (/Users/hhimanshu/code/prsnl/ts/ts-react-components-lib/node_modules/webpack/lib/webpack.js:31:9)
    at /Users/hhimanshu/code/prsnl/ts/ts-react-components-lib/node_modules/@size-limit/webpack/run-webpack.js:5:20
    at new Promise (<anonymous>)
    at runWebpack (/Users/hhimanshu/code/prsnl/ts/ts-react-components-lib/node_modules/@size-limit/webpack/run-webpack.js:4:10)
    at Object.step40 (/Users/hhimanshu/code/prsnl/ts/ts-react-components-lib/node_modules/@size-limit/webpack/index.js:88:38)
    at /Users/hhimanshu/code/prsnl/ts/ts-react-components-lib/node_modules/size-limit/calc.js:17:47
    at Array.map (<anonymous>)
    at step (/Users/hhimanshu/code/prsnl/ts/ts-react-components-lib/node_modules/size-limit/calc.js:16:29)
    at calc (/Users/hhimanshu/code/prsnl/ts/ts-react-components-lib/node_modules/size-limit/calc.js:44:42)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)

```

**If the current behavior is a bug, please provide the steps to reproduce.**
- Please checkout `hhimanshu/update-deps` branch from https://github.com/hhimanshu/ts-react-components-lib
- Run `yarn install`
- Run `yarn size`

**What is the expected behavior?**
The command should have ran successfully

**Other relevant information:**
The `package.json` is available at https://github.com/hhimanshu/ts-react-components-lib/blob/hhimanshu/update-deps/package.json
There is a Github Action demonstrating this issue at https://github.com/hhimanshu/ts-react-components-lib/pull/7/checks?check_run_id=3163107139

webpack version:  
Node.js version
```
➜  ts-react-components-lib git:(hhimanshu/update-deps) ✗ node -v
v14.17.0
➜  ts-react-components-lib git:(hhimanshu/update-deps) npm -v
7.17.0
➜  ts-react-components-lib git:(hhimanshu/update-deps)
```

Operating System: Mac
Additional tools:

**Comment by ai** [comment]
Are you replacing webpack config in Size Limit?

Seems like you have an issue in webpack config. I can’t help you with it (it is advanced technique).

I recommend to not do it for web application. It is better to build your app in a separated step and then use `@size-limit/file` to check the output files.

**Comment by hhimanshu** [comment]
@ai 
I am not replacing anything, the configuration in master is same as the feature branch. Also, it is not for the web application. Is there a reason you closed it before discussing?

**Comment by ai** [comment]
We can always re-open issue again.

Can you post `npx size-limit --debug` output?

**Comment by hhimanshu** [comment]
fantastic, thanks for the catch. The issue was that the file names have changed, failing to which the array was coming empty. Once I fixed the [fixed the file names](https://github.com/hhimanshu/ts-react-components-lib/pull/7/commits/165c0f6318a0deecea3d2edf8e985913b2a5eeff), the `size-limit` runs successfully

```
size-limit
✔ Adding to empty webpack project

  dist/ts-react-components-lib.cjs.production.min.js
  Size limit: 10 kB
  Size:       696 B with all dependencies, minified and gzipped

  dist/ts-react-components-lib.esm.js
  Size limit: 10 kB
  Size:       696 B with all dependencies, minified and gzipped

✨  Done in 3.06s.
```

Now I see Github Action failing at https://github.com/hhimanshu/ts-react-components-lib/pull/7/checks?check_run_id=3164196064

This seems to be related to https://github.com/andresz1/size-limit-action

**Comment by ai** [comment]
Seems like we need to improve error message for this case

**Comment by hhimanshu** [comment]
I opened issue at https://github.com/andresz1/size-limit-action/issues/62

**Comment by ai** [comment]
I improved error message in CLI tool c87a49e

**Comment by hhimanshu** [comment]
But this is not handling https://github.com/ai/size-limit/issues/241#issuecomment-886897839, right?

**Comment by ai** [comment]
Yeap. It is just a better error message, which make it clear that Size Limit doesn’t see any file.
