### ISSUE TITLE
Running without installation

### ISSUE THREAD

**Issue by telamon** [ai/size-limit#243]
hey when i attempt to run:
```bash
npx size-limit
```
inside of my module i'm met with an error of installing some profile dependencies...
I'm not too keen on trashing down a lib with more deps just to check it's size, kinda counterproductive...
So i guess either the stand-alone cli functionality should either be repaired or the image in the readme removed?
Thanks! :+1:

**Comment by ai** [comment]
You must add Size Limit to `package.json` because of the way how we look for Size Limit plugins.

There is no way to do it from `npx size-limit` without installing dependencies.

It should be something like:

```sh
npm install size-limit
npm install @size-limit/file # or any other plugin
npx size-limit # and now you can run Size Limit because `npm install` added it to package.json
```

**Comment by telamon** [comment]
Sorry to hear that, let me know if you decide to redesign this util. :+1:
