### ISSUE TITLE
Prints "Adding to empty webpack project" to stderr

### ISSUE THREAD

**Issue by anilanar** [ai/size-limit#250]
`yarn size-limit` prints "Adding to empty webpack project" at the beginning and `yarn size-limit 2> /dev/null` does not. That means `size-limit` prints "Adding to empty webpack project" into `stderr` which is considered a warning/error by some CI tools and causes CI to fail.

We can ignore that output by using `2> /dev/null` but that can cause loss of valuable information if/when something actually goes wrong.

Q: Why print to `stderr` instead of `stdout`?

**Comment by ai** [comment]
We are printing to `stderr` to be able to save results in a file without loaders:

```
npx size-limit > result.txt
```

[`mico-spinner`](https://github.com/enemycnt/mico-spinner), as I believe, uses a logic “what is not main result should be in `stderr`”.

I can change stream if you give me some proofs, that it is not UNIX way or something similar.

**Comment by anilanar** [comment]
Makes sense, thanks :+1:
