### ISSUE TITLE
Size is reported as 0 bytes since upgrading to 6.x

### ISSUE THREAD

**Issue by ezzatron** [ai/size-limit#261]
I'm trying to upgrade `size-limit` to `6.0.3` in my projects. I'm also using `@size-limit/preset-small-lib` at the same version. I haven't made any changes to my config or code, but I'm now [seeing sizes of 0 bytes](https://github.com/snout-router/regexp/runs/3876981489?check_suite_focus=true#step:4:36):

```
/opt/hostedtoolcache/node/14.18.0/x64/bin/npx size-limit --json
[
  {
    "name": "dist/index.js",
    "passed": true,
    "size": 0
  },
  {
    "name": "dist/index.es.js",
    "passed": true,
    "size": 0
  }
]
```

Versus [the output I get from `size-limit@^5.0.3`](https://github.com/snout-router/regexp/runs/3876981489?check_suite_focus=true#step:4:91):

```
/opt/hostedtoolcache/node/14.18.0/x64/bin/npx size-limit --json
[
  {
    "name": "dist/index.js",
    "passed": true,
    "size": 56
  },
  {
    "name": "dist/index.es.js",
    "passed": true,
    "size": 66
  }
]
```

This results in reports indicating that I've [removed 100% of my code](https://github.com/snout-router/regexp/pull/7#issuecomment-941791261):

<img width="429" alt="Screen Shot 2021-10-13 at 10 42 51 am" src="https://user-images.githubusercontent.com/100152/137047759-299b66fe-6d07-464c-a80a-476082a5be27.png">

**Comment by ai** [comment]
Change `path: 'dist/index.js',` → `path: './dist/index.js',` (add `./` to the start of the path)

**Comment by ai** [comment]
I am working on a better solution

**Comment by ai** [comment]
@ludofischer webpack 5 started to remove any exports from bundles if we do not pass `import` option.

Any idea how to disable it for non-`import` cases?

**Comment by ezzatron** [comment]
You might also be interested to know that the `./` path prefix was not necessary to get results, only manually specifying the `import` option was necessary: https://github.com/snout-router/regexp/runs/3894148976?check_suite_focus=true#step:5:25

P.S. I'm also getting some pretty surprising results for the size of the CJS version, but I'll make another issue for that if necessary.

**Comment by ai** [comment]
@ludofischer I added `shakable-webpack-5` with a test for this case

**Comment by ai** [comment]
> In my case all .cjs files' sizes were increased approximately by 140-150 bytes.

@yumauri we already subtract wrapper size from the bundle size.

In my case, I got 20-30 extra bytes, but because of the opposite reason. webpack 5 wrapper is very small and gzip now can use it to reduce size of your JS code.

So for my case the result become bigger, but a little more fair.

**Comment by ludofischer** [comment]
> Any idea how to disable it for non-import cases?

Sorry, I don't know about this. I would need to look into the webpack docs :-)

> In my case all .cjs files' sizes were increased approximately by 140-150 bytes.

When we calculate the bunndle size, we subtract the 'empty' bundle size to get the final bundle size.  With webpack 4 even bundling empty code would create some wrappers. I think what might be happening is that with webpack 5 the empty bundle size is almost 0, so adding any code makes a larger difference. 
Why not just report the webpack bundle size without performing any subtraction, though?

**Comment by ezzatron** [comment]
> Sorry, I don't know about this. I would need to look into the webpack docs :-) Apparently you can use https://webpack.js.org/configuration/optimization/#optimizationusedexports but it looks like it's going to disable tree shaking even for transitive dependencies, so it will report a larger bundle size than what will happen in production. With tree-shaking the question 'how much does this add to the bundle' has more than one answer. It might really be zero if the user just imports your library without calling it…

To be clear, what I expected by leaving off `import` was essentially that it would mean the same thing as `import * as x from 'my-module'`. Basically, what is the size if you use every named and default export the module has. I believe this was the behaviour under the previous version of `size-limit`.

> Why not just report the webpack bundle size without performing any subtraction, though?

My guess is that most developers would want to know how much "extra" bundle size they'd be getting by adding the library to an existing project that already uses Webpack, and hence they've already decided that they're comfortable with the overhead of Webpack itself. It's much less useful to know how big a library would be if you bundled only that singular library and nothing else.

**Comment by ai** [comment]
@ludofischer we can add some optional like `importAll: true` or `import: "*"` and use [`import`-option code](https://github.com/ai/size-limit/blob/main/packages/webpack/get-config.js#L12-L24) to generate file like:

```js
import * as all from '../entry.js'
console.log(all)
```

**Comment by ludofischer** [comment]
> It is OK for 1-10K projects, but not so good for projects like from issue owner.

What about outputting best/worst case numbers by default (so both the current configuration and using the `console.log(all) trick`)? That way people do not need to bother with extra options.

**Comment by ai** [comment]
> What about outputting best/worst case numbers by default (so both the current configuration and using the console.log(all) trick)? That way people do not need to bother with extra options.

Hm. I like the idea.

**Comment by ezzatron** [comment]
I think this issue has been fixed for some time now, and could probably be closed?
