### ISSUE TITLE
Add `@size-limit/esbuild` plugin

### ISSUE THREAD

**Issue by ai** [ai/size-limit#267]
Moving to esbuild will reduce `node_modules` size and improve performance

**Comment by Windrushfarer** [comment]
Hey, I found this issue in `cultofmartians` :) I will take a look at it, doesn't look too complicated

**Comment by ai** [comment]
Yeap. We need to cover the simple case of libraries like `nanoid` (when we have multiple JS files with `import` or `require()` and `process.env.NODE_ENV`). No CSS or any other webapp bundling problems.
