### ISSUE TITLE
Support Node 15 in package engines declaration

### ISSUE THREAD

**Issue by drewlustro** [ai/size-limit#269]
Packages published by this monorepo curiously do not support Node 15:

```js
"engines": {
  "node": "^12.0.0 || ^14.0.0 || >=16.0.0"
}
```
https://github.com/ai/size-limit/blob/main/packages/file/package.json#L16-L18

I acknowledge that Node 14/16 are the bigger LTS fish, but consider:

- Node 15 is the first node version to natively support Apple Silicon.
- Node 15 is not uniquely incompatible compared to Node 16.
- Node 16 also supports Apple Silicon, but it forces a more dramatic waterfall of package upgrades. The ecosystem is still catching up.

## Workaround

```sh
yarn install --ignore-engines
```

**Comment by ai** [comment]
Because odd versions are unstable versions. You should not use them in production.

**Comment by ai** [comment]
Another reason: Node.js Foundation doesn’t support Node.js 15 anymore. There is no security update and you should not use it anywhere right now.

https://nodejs.org/en/about/releases/
