### ISSUE TITLE
Peer dependency issue on `@size-limit/preset-small-lib`

### ISSUE THREAD

**Issue by browniebroke** [ai/size-limit#275]
I recieved a couple of PRs from Renovate to update to size-limit v7 but they were failing with `ERESOLVE unable to resolve dependency tree`. The PR was trying to update both packages at once:

- `size-limit`: 6.0.4 -> 7.0.4
- `@size-limit/preset-small-lib`: 6.0.4 -> 7.0.3

The error is because `preset-small-lib` has a peer dependency on `size-limit` [pinned to the exact same version](https://github.com/ai/size-limit/blob/3dbc492ceca59f378330f80b2ce2d93709865adc/packages/preset-small-lib/package.json#L15-L17), so 7.0.4 isn't seen as compatible with 7.0.3.

It looks like the version was [updated on GitHub](https://github.com/ai/size-limit/blob/7352d9087e2152cb8fc30b88351eaa7cd350bd8f/packages/preset-small-lib/package.json#L15-L17) but it's not published to npm (latest version is 7.0.3). 

The automatic update should have updated both packages to 7.0.4, but one isn't published, hence the error. Is there any chance we could get `@size-limit/preset-small-lib` 7.0.4 published on npm? I'm pinning them both to 7.0.3 for now, but I thought you might want to know about this.

**Comment by ai** [comment]
Thanks. I just released `@size-limit/preset-small-lib@7.0.4`.

**Comment by browniebroke** [comment]
Thanks!
