### ISSUE TITLE
check web worker size

### ISSUE THREAD

**Issue by jeetiss** [ai/size-limit#276]
Webpack 5 supports native workers out of the box, is it possible to check the size of web workers with size-limit?

I tried to check support but seems size-limit doesn't check all worker chunks on default? 

here is the minimal setup https://github.com/jeetiss/size-limit-web-worker

Do you have any ideas or suggestions for a proper `web-worker` size check?

**Comment by ai** [comment]
Can you set worker file in `path` (with `*` in hash)?
