### ISSUE TITLE
Unsupported URL Type "workspace:": workspace:7.0.5

### ISSUE THREAD

**Issue by Alduino** [ai/size-limit#279]
In version 7.0.6, running `npm install` in a package with `@size-limit/preset-small-lib` installed fails with the error in the title.

I think it is because preset-small-lib depends on size-limit packages with versions that require exactly `workspace:7.0.5`, which doesn't exist any more. Maybe this should be `workspace:^7.0.5`? ([packages/preset-small-lib/package.json](https://github.com/ai/size-limit/blob/main/packages/preset-small-lib/package.json))

**Comment by ai** [comment]
Thanks. Fixed c65cb59

**Comment by ai** [comment]
The fix was released in 7.0.8.
