### ISSUE TITLE
Idea: .size-limit config file

### ISSUE THREAD

**Issue by juanbrujo** [ai/size-limit#28]
Instead of: _Add size-limit section to package.json and size script:_

This lib could have it's own dotfile `.size-limit` for configuration info

**Comment by ai** [comment]
Hm. Yeap, good idea. For example, with same JSON format as in `package.json`.

I will have time for it only in next weeks (sorry, I am preparing for talk).

**Comment by mrmartineau** [comment]
Might I suggest using https://github.com/davidtheclark/cosmiconfig for this so that people have the option to choose how to write their config.

**Comment by ai** [comment]
@mrmartineau absolutely, I had good experience with cosmicconfig in PostCSS.

Do you want to send PR?

**Comment by ai** [comment]
Fixed by @borovik96 in https://github.com/ai/size-limit/pull/32

**Comment by ai** [comment]
Released in 0.13
