### ISSUE TITLE
Downstream deps causing issues during postinstall for scripts

### ISSUE THREAD

**Issue by rmarkins-godaddy** [ai/size-limit#280]
the `estimo` package which depends upon `puppeteer-core` is causing issues when doing an `npm install` as the script fails due to their `exports` package.json change. Here are both issues I have filed

https://github.com/mbalabash/estimo/issues/36

https://github.com/puppeteer/puppeteer/issues/7986

**Comment by ai** [comment]
What version we should lock?

**Comment by rmarkins-godaddy** [comment]
@ai 13.2.0 should be good enough

**Comment by ai** [comment]
I can lock only `estimo` version. If you know a solution, please send PR.

**Comment by rmarkins-godaddy** [comment]
@ai looks like puppeteer has reverted their exports change and published a new patch for this so downstream `estimo` might be unblocked for now. Closing this issue unless something else comes up
