### ISSUE TITLE
enable experiments in webpack config

### ISSUE THREAD

**Issue by opeologist** [ai/size-limit#282]
i have enabled the use of topLevelAwait in my "big lib" that i'd like to use the preset for, but upon attempting to have the preset's webpack app use the bundle, it immediately fails saying `topLevelAwait` isn't enabled

is there some way to customize the webpack config that's used for that preset that i'm not aware of? thanks!

**Comment by ai** [comment]
Yes, there is `modifyWebpackConfig` function in config (you need use JS version of config) where you can modify webpack config.

Also you can use `config` option to set path to new webpack config.
