### ISSUE TITLE
Feature request: support monorepos by logging the package name

### ISSUE THREAD

**Issue by Offirmo** [ai/size-limit#283]
Thanks a lot for this tool!

I'm using a [monorepo](https://monorepo.tools/). When launching a size-limit check on my whole monorepo, I get something like that:

```
✔ Adding to empty esbuild project

  dist/src.es2021/index.js
  Size limit: 250 B
  Size:       184 B with all dependencies, minified and gzipped

  dist/src.es2021.cjs/index.js
  Package size limit has exceeded by 31 B
  Size limit: 250 B
  Size:       281 B with all dependencies, minified and gzipped

  Try to reduce size or increase limit in "size-limit" section of package.json
```
and then the command stop.

The problem is... I have no idea which package of my monorepo caused this error 😅 it's not named anywhere in the output. Could we add an extra line such as: **`Checking size limit for package "@foo/bar"...`**

```
Checking size limit for package "@foo/bar"...
✔ Adding to empty esbuild project

  dist/src.es2021/index.js
...
```
Thanks a lot!

**Comment by ai** [comment]
Will it be a better way to add printing the package name in `script`?

```json
  "scripts": {
    "size": "echo '@foo/bar' && size-limit"
  }
```

**Comment by Offirmo** [comment]
@ai yes it could work. It doesn't scale very well, though. Need dozens of package.json altered.

Another solution would be for the monorepo tooling to prefix the lines with the repo name.

I understand that the responsibility is unclear.

**Comment by ai** [comment]
> It doesn't scale very well, though.

You can write a small wrapper on top of Size Limit CLI.

I think that it is rare case when we have to change output for all Size Limit users and increase CLI code complixity :(.
