### ISSUE TITLE
Add the limit to the JSON object

### ISSUE THREAD

**Issue by elliotwestlake** [ai/size-limit#284]
It'd be great to have the limit there in the JSON object.

We could then use this in the `size-limit` action so if it exceeds the limit you can easily see by how much

**Comment by ai** [comment]
Do you ask about webpack or rebuild plugins of Size Limit?

The `@size-limit/file` should work with any types of files.

**Comment by wizardels** [comment]
`esbuild` 

When running: `npx size-limit --json`

The response currently looks like:
```json
[
  {
    "name": "account",
    "passed": true,
    "size": 4306
  },
  {
    "name": "diaries",
    "passed": true,
    "size": 510
  }
]
```

However it would be good if it looked like this:
```json
[
  {
    "name": "account",
    "passed": true,
    "limit": 10000,
    "size": 4306
  },
  {
    "name": "diaries",
    "passed": true,
    "limit": 1000,
    "size": 510
  }
]
```

**Comment by wizardels** [comment]
Awesome, sounds good to me!

**Comment by ai** [comment]
All users have right to open PR.

Click `Fork` on top left corner, clone your fork to your computer, create branch `git checkout -b add-limit-to-json`, add changes, push them to GitHub, then you will have `Open pull request` button on GitHub.

**Comment by equinusocio** [comment]
THE END

**Comment by ai** [comment]
`sizeLimit` was already added to JSON output

**Comment by equinusocio** [comment]
Yes, i meant when asking to contribute to OSS and opening PR people disappear :D

**Comment by elliotwestlake** [comment]
Sorry about this! I had intended to get round to contributing, wasn't intentional :)
