### ISSUE TITLE
Incorrect config parsing

### ISSUE THREAD

**Issue by JounQin** [ai/size-limit#289]
https://github.com/ai/size-limit/blob/7461f32cddc403fe8ee6db4f8d43c9a76bfc9c52/packages/size-limit/run.js#L67-L72

It only looks up for `package.json` for plugins, and throws if no plugin found from `package.json`.

**Comment by JounQin** [comment]
https://github.com/ai/size-limit#config

@ai

**Comment by ai** [comment]
> https://github.com/ai/size-limit#config

This config is for limits.

It is not for plugins.

Our API is that Size Limit takes plugins from `package.json`.

Why do you need plugins in the config?

**Comment by JounQin** [comment]
> Size Limits supports three ways to define config.

I don't quite understand

> This config is for limits.
>
> It is not for plugins.

How should we define plugins in `package.json`?

> Why do you need plugins in the config?

I'm trying to use `modifyWebpackConfig`.

**Comment by JounQin** [comment]
Besides, I want to use `modifyWebpackConfig` because I want to external all node modules from size calculation.

It seems no `esbuild` config to set.

**Comment by ai** [comment]
> I don't quite understand

It means 3 different file names `.size-limit.json` or `.size-limit.js` or `size-limit` section in `package.json`

> How should we define plugins in package.json?

Just add them to `devDependencies`.

For instance by:

```sh
npm install --save-dev @size-limit/webpack
```

**Comment by ai** [comment]
I am closing this issue since it is a question, not an issue.

Feel free to continue discussion with questions.

**Comment by JounQin** [comment]
@ai Please review #290
