### ISSUE TITLE
Does this work for a list of chunks and not a main bundle file?

### ISSUE THREAD

**Issue by gkatsanos** [ai/size-limit#296]
![image](https://user-images.githubusercontent.com/1768834/187236075-9db71cb9-e995-4efe-9218-f704a918170a.png)

how does one instruct size-limit to check all of these? Does this work with a webpack analyzer json file?

**Comment by ai** [comment]
> Does this work for a list of chunks and not a main bundle file?

You can try something like `/dist/*.js`.

> Does this work with a webpack analyzer json file?

No

**Comment by ai** [comment]
For questions you can use [Discussions](https://github.com/ai/size-limit/discussions) section of these repo

**Comment by lkraav** [comment]
> For questions you can use [Discussions](https://github.com/ai/size-limit/discussions) section of these repo

It seems Discussions is turned off?

**Comment by ai** [comment]
Should work. How the page looks like on our machine?

**Comment by lkraav** [comment]
> Should work. How the page looks like on our machine?

It loads now, whereas it 404-d before because I'm fairly certain Discussion was disabled.
