### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'javaScript')

### ISSUE THREAD

**Issue by unional** [ai/size-limit#310]
On WSL
With Node 18.12.1
With puppeteer 13.7.0
With estimo 2.3.6
With size-limit 8.0.1

```sh
Error: Failed to launch the browser process! spawn /home/homa/code/mocktomata/node_modules/.pnpm/estimo@2.3.6/node_modules/estimo/temp/chrome/linux-982053/chrome-linux/chrome ENOENT

✖ Running JS in headless Chrome
ERROR  TypeError: Cannot read properties of undefined (reading 'javaScript')
  at getTime (/home/homa/code/mocktomata/mocktomata/node_modules/.pnpm/@size-limit+time@8.0.1_size-limit@8.0.1/node_modules/@size-limit/time/get-running-time.js:29:22)
```

on this line:

```js
let estimo = require('estimo')

...

  value += perf[0].javaScript / 1000
```

**Comment by ai** [comment]
Seems like you need to report to `estimo` since it send back `undefined`

**Comment by unional** [comment]
Sure. I checked and it returns `[]`

**Comment by unional** [comment]
Since the downstream issue might take some time to fix, should we fix the usage here?
default the value to 0, and maybe emit a warning about it.
The filename `/tmp/size-limit-DnCRqgCfYvwJ1rc8ocpJI/index.js` might not make much sense in the warning thou.

**Comment by ai** [comment]
If value is `0` it is still an issue. We can’t process it with a rational results.

**Comment by unional** [comment]
Is there a way to disable the time tracking?

It's blocking me from releasing my package. :(
https://github.com/mocktomata/mocktomata/actions/runs/4159708870/jobs/7196155664

**Comment by ai** [comment]
Just avoid the `time` plugin (you may need to change the preset).

**Comment by unional** [comment]
> Just avoid the `time` plugin (you may need to change the preset).

Sure. Changed from `@size-limit/preset-big-lib` to `@size-limit/preset-small-lib`. thx.
