### ISSUE TITLE
multiple checks with `--why` only kept last `report.html`

### ISSUE THREAD

**Issue by unional** [ai/size-limit#311]
e.g.:

```
// package.json
{
  "size-limit": [
    {
      "path": "./cjs/index.js",
      "limit": "15 kb"
    },
    {
      "path": "./esm/index.js",
      "limit": "15 kb"
    },
    {
      "path": "./tslib/index.js",
      "limit": "15 kb"
    }
  ]
}
```

Running `size-limit --why` (using `esbuild` and `esbuild-why`) will create a `report.html` containing the result of the last one (`tslib`) as the previous ones are overwritten.

I can change it to add `report-{x}.html`, but a better way is giving each check a name, and name the output as `report-{name}.html`?

Currently the `check` contains a `name`, but it is the entry file name:

```
{
  path: './tslib/index.js',
  limit: '15 kb',
  files: [ 'D:\\code\\unional\\type-plus\\tslib\\index.js' ],
  name: './tslib/index.js',
  sizeLimit: 15000,
  ...
}
```

**Comment by ai** [comment]
> but a better way is giving each check a name, and name the output as report-{name}.html?

check already has `name` but it could contain spaces.

Maybe `report-1.html` will be better.

**Comment by unional** [comment]
Just checked. I can config it:

```
    {
      "name": "tslib",
      "path": "./tslib/index.js",
      "limit": "15 kb"
    }
```

produce:
```
{
  name: 'tslib',
  path: './tslib/index.js',
  limit: '15 kb',
  files: [ 'D:\\code\\unional\\type-plus\\tslib\\index.js' ],
  sizeLimit: 15000,
  ...
}
```

I can use that and fall back to `{n}` if it contains invalid characters.

**Comment by unional** [comment]
Zero-based or one-based? 😛 

`esbuild-why-0.html` vs `esbuild-why-1.html`

**Comment by ai** [comment]
Let’s start from `1` :)

**Comment by unional** [comment]
Yep, that's what I'm doing.
