### ISSUE TITLE
Clarify path option

### ISSUE THREAD

**Issue by sapegin** [ai/size-limit#33]
Which version should I specify in the `path` option: source code or a compiled one (the same I have in the `main` field of package.json)?

**Comment by ai** [comment]
1. For an application, you specify bundle file and use `webpack: false`.
2. For an open-source library, you specify compiled sources, which will be published to npm.

Do you want to send PR to docs? It is always better for new users to fix docs, since they saw problem places.

**Comment by sapegin** [comment]
Thanks! I’ll try to send a PR. I’m also adding a tiny section on size-limit to [the book](https://github.com/survivejs/maintenance-book) ;-)
