### ISSUE TITLE
Switch from GZIP to Brotli by default

### ISSUE THREAD

**Issue by kytta** [ai/size-limit#343]
Brotli, as we know, is a more superior compression algorithm; fast & effective. According to Can I Use, [97% of devices can use Brotli](https://caniuse.com/brotli). It's widely adopted by the servers, too: nginx, Apache, LiteSpeed, lighttpd, Caddy, and others. Big CDNs like [Fastly](https://www.fastly.com/blog/brotli-is-great-at-making-things-small-and-no-we-arent-talking-about-the) and [Cloudflare](https://blog.cloudflare.com/this-is-brotli-from-origin/) are enabling it by default.

Wouldn't it make sense for size-limit to flip the switch, too, and show the "brotlied" result by default, making GZIP opt-in and encouraging people to switch their infrastructure?

**Comment by ai** [comment]
Sounds like a good idea. But I will ask in Twitter first to collect the feedback.

**Comment by ai** [comment]
Here is PR https://github.com/ai/size-limit/pull/346

**Comment by ai** [comment]
Here is a good statistics about the real web traffic in 2022 https://almanac.httparchive.org/en/2022/cdn#brotli-adoption

* 47% of CDN traffic is Brotli
* 25% of self-hosted servers

I think it is pretty solid numbers. In 2023, they will be better. And this is the whole traffic. Size Limit users is a little more advanced.

![Screenshot from 2023-11-11 07-11-26](https://github.com/ai/size-limit/assets/19343/45e26175-4c44-4548-90c9-f92a251d48e9)

**Comment by ai** [comment]
Released in 11.0.
