### ISSUE TITLE
plugins are `import`ed with `require.resolve` which will resolve `commonjs` entry for dual package

### ISSUE THREAD

**Issue by JounQin** [ai/size-limit#344]
https://github.com/ai/size-limit/blob/f2493379fefc00559af2a8c54fc52cedbbc9b0bd/packages/size-limit/load-plugins.js#L30-L34

This is unexpected for third-party plugins.

**Comment by JounQin** [comment]
Workaround: I publish ESM-only plugin now.

**Comment by ai** [comment]
Yes, I think let’s move to ESM as a requirement for Size Limit plugin.

It doesn’t look too complicated since we have only a few third-party plugins.

**Comment by JounQin** [comment]
ESM is not required even when we use `import()` directly, the current issue is we're preferring commons over ESM incorrectly for dual package.

**Comment by ai** [comment]
The fix was released in 10.0.3.
