### ISSUE TITLE
Why doesn't it use itself to check its bundle size?

### ISSUE THREAD

**Issue by pke** [ai/size-limit#35]
Great project!
It would be really meta if this package would check its own size. Would that make sense?

**Comment by ai** [comment]
@pke good question :). There are 2 reasons:

1. Size Limit is not a client-side library. So there are no reasons to reduce its size.
2. Since Size Limit uses webpack and gzip, it could not be easily compiled for a browser.

**Comment by pke** [comment]
I knew it was just too meta :) hehe
Anyway we will roll out size-limit to our CI now.
