### ISSUE TITLE
Allow customize error message

### ISSUE THREAD

**Issue by dartess** [ai/size-limit#350]
Now I get standard message like `Try to reduce size or increase limit at .size-limit.json`.

It would be great to be able to change this message, including setting a different message for different groups of files, like this:

```
  "size-limit": [
    {
      "path": "main.js",
      "limit": "500 ms",
      "message": "Call Hugo"
    },
    {
      "path": "page-index-*.js",
      "limit": "100 ms",
      "message": "Call Ghostbusters"
    },
  ]
```

**Comment by ai** [comment]
Please send PR
