### ISSUE TITLE
Support `.size-limit.mjs` config file

### ISSUE THREAD

**Issue by aryaemami59** [ai/size-limit#352]
I would be more than willing to submit a PR if you think this is something worth considering.

**Comment by ai** [comment]
Yes. If we support `.js` file, we should support `.mjs`/`.cjs` files too.

Please send PR to save your name in the project’s history.

**Comment by aryaemami59** [comment]
@ai 

> Yes. If we support `.js` file, we should support `.mjs`/`.cjs` files too.
> 
> Please send PR to save your name in the project’s history.

Wonderful, one PR coming right up!
