### ISSUE TITLE
how to use with react-starter package?

### ISSUE THREAD

**Issue by maxlapshin** [ai/size-limit#36]
There are starter packages like https://github.com/MacKentoch/react-bootstrap-webpack-starter

It is not clear what to put into size-limit configuration, because this project has reference to non-existing file:
https://github.com/MacKentoch/react-bootstrap-webpack-starter/blob/master/package.json#L5

Can you give a hint: how to configure size-limit for such project?

**Comment by ai** [comment]
In this case, you need to run Size Limit after build step:

```
"scripts": {
  "size": "npm run prod && size-limit"
},
"size-limit": [
  {
    "path": "docs/public/assets/app.js",
    …
  }
]
```
