### ISSUE TITLE
size-limit fails to detect paths/files containing unescaped characters

### ISSUE THREAD

**Issue by byronhulcher** [ai/size-limit#369]
I am working in a next.js project with a page at path `/pages/[...rest.tsx]` which follows [next's guidance for catch-alls](https://nextjs.org/docs/pages/building-your-application/routing/dynamic-routes#catch-all-segments)

However when running size-limit on the build artifact from my project I get an error like

```
  /[...rest]
  Size Limit can’t find files at build/static/chunks/pages/[...rest]-ad704487c50fb012.js
```

I believe this is due to [how size limit is calling globby](https://github.com/ai/size-limit/blob/main/packages/size-limit/get-config.js#L157).  [globby](https://www.npmjs.com/package/globby) (more specifically, fast-glob) expects you [to escape your paths before passing them over](https://github.com/mrmlnc/fast-glob?tab=readme-ov-file#escapepathpath). [fast-glob even provides a helper for this](https://github.com/mrmlnc/fast-glob?tab=readme-ov-file#escapepathpath).

I believe that passing all of the paths through this function will fix this issue, in fact I have tested it locally and will file a PR.  I am optimistic we can solve this together 🙂

**Comment by ai** [comment]
Escaping `!` will mean that users will not be able to use glob features. So I think it is on user to escape patterns if they do not need to use glob feature.
