### ISSUE TITLE
Enable options to load different config files from command-line or npm script

### ISSUE THREAD

**Issue by filipposarzana** [ai/size-limit#37]
Probably would be a great improvement to have and option to load different configuration files either from `npm run size` or from **cli**

Just like `.dotenv` file you could have `.size-limit` which will always be the default one and eventually `.size-limit.prod`

**Comment by ai** [comment]
Hm. Why do you need different environment? Maybe there is a more simple way.

**Comment by SivanMehta** [comment]
If you're just looking for cli options you can just disable the internal webpack and manually run your own webpack build.

For example, you can try adding this within your `package.json`

```json
"scripts": {
  "build": "webpack --config your-custom-config-file.js dist/output.js",
  "size": "npm run build && size-limit"
},
"size-limit": [
  {
     "limit": "300 KB",
     "webpack": false,
     "path": "dist/output.js"
  }
]
```

Now, `npm run size` will just run with whatever configuration files you provide.

**Comment by ai** [comment]
All config options are available by CLI option. So if you want to have different configs:

```sh
size-limit 10 KB app.js --no-webpack 
```

I think CLI options will be enough.

But I will open this feature request again when somebody will show me use case for different configs.
