### ISSUE TITLE
Support for disabling gzip

### ISSUE THREAD

**Issue by tivac** [ai/size-limit#38]
I build web apps for a slightly odd environment (game UIs) and while I care about bundle size we don't gzip any of our assets. They're compressed as part of the entire game data so it just doesn't make much sense. 

Since our bundles won't be gzipped when shipped to consumers it means that the current checking that `size-limit` does is a little odd. Would it be possible to get an option to disable the gzip before doing the size comparison?

**Comment by ai** [comment]
Good idea (I aill add `gzip: false`). Sorry, it is bar time for me right now ;). I will try to implement it tomorrow.

**Comment by ai** [comment]
Done ba044df

**Comment by ai** [comment]
Released in 0.14.
