### ISSUE TITLE
Support a description key.

### ISSUE THREAD

**Issue by oliviertassinari** [ai/size-limit#39]
The `.size-limit` file on [Material-UI side is growing](https://github.com/mui-org/material-ui/pull/9853). I have started adding description information so external contributors can better understand why their build is failing.

![capture d ecran 2018-01-12 a 22 29 52](https://user-images.githubusercontent.com/3165635/34895966-3b89364a-f7e8-11e7-8e71-d532a8e1e1bf.png)

This is a suggestion, I'm not 100% convinced it's a good idea. Here it is.
What do you think of displaying the description in the output of the CLI?

**Comment by ai** [comment]
So, you want `The main bundle of the documentation` instead of `.next/app.js`? I think it is a great idea! :+1: 

I will try to implement it tomorrow.

**Comment by oliviertassinari** [comment]
@ai I'm happy you like my proposition :).

**Comment by ai** [comment]
Done 360735a

I used `name` instead of `description` since it is shorter and more clear.

**Comment by oliviertassinari** [comment]
@ai Thanks, I'm updating our .size-limit :).

**Comment by ai** [comment]
I will release it 30 minutes later
