### ISSUE TITLE
Update webpack to v4 for .mjs support

### ISSUE THREAD

**Issue by jaydenseric** [ai/size-limit#41]
Packages should publish `.mjs` (ESM) files sibling to `.js` (CJS) files and use extensionless imports to support both Node.js native modules and traditional CJS environments. I'm already using `.mjs` in 4+ packages and use native modules for a few APIs.

Webpack v4 beta supports `.mjs` while v3 has a lot of issues; namely it resolves `.js` instead of `.mjs` for extensionless imports. This stuffs up tree-shaking and incorrectly results in almost identical `size-limit` results for `.mjs` and `.js` entries.

The latest [webpack release](https://github.com/webpack/webpack/releases) is v4.0.0-beta.2. According to [this tweet](https://twitter.com/wSokra/status/937937284808265728), v4 will ship at least a month after the first release candidate. This could be months away; I don't think waiting for a "stable" release is worth delaying an update.

**Comment by ai** [comment]
Good point. I am thinking to release mjs packages as well. Do you want to send PR?

**Comment by ai** [comment]
Released in 0.15.
