### ISSUE TITLE
TypeScript support

### ISSUE THREAD

**Issue by thasmo** [ai/size-limit#44]
Does `size-limit` support TypeScript?

*.size-limit*
```js
[
  {
    path: "assets/main.ts",
    webpack: false,
  }
]
```

> npm run size-limit
```sh
Package size: 357 B
With all dependencies, minified and gzipped
```

Would be awesome to have this support TypeScript if possible.

**Comment by ai** [comment]
There is two way to do it:

1. Run Size Limit on your `dist/` dir with compiled JS files. It is recommended way.
2. Use custom webpack config. Not recommended because result could be a little different from real npm package.

**Comment by thasmo** [comment]
@ai, thanks for the quick response. Does that mean `size-limit` simply sums up all files' sizes and displays the total size?

**Comment by ai** [comment]
Nope. Size Limit emulates “simple user”. It creates empty and simple webpack project in the memory, install your library and calculates project size difference.

Because it emulates simple user, it doesn't have TS support. Since your library users will not add special TS loaders for your library.

**Comment by thasmo** [comment]
But for `Run Size Limit on your dist/ dir with compiled JS files. It is recommended way.` it would just sum up all files' sizes, I guess?

**Comment by ai** [comment]
Nope. It will load `dist/index.js` in that empty project in the memory.

**Comment by ai** [comment]
Sum all files is not the best way to control size. In my experience the most popular problems with the size happen because of dependencies and webpack's polyfills for Node modules (like when you are using `process`).

This is why we always try to calculate real cost of your library.

(If you really need just files sum you can do it by `webpack: false, path: "dist/*"`, but I don't recommend it)

**Comment by thasmo** [comment]
I'm not sure I understand this. In my final `dist` directory I have these files:
* main.js
* main.js.gz
* main.js.br
* vendor.js
* vendor.js.gz
* vendor.js.br
* main.css
* main.css.gz
* main.css.br
* chunks/0.js
* chunks/0.js.gz
* chunks/0.js.br
* icons/{multiple}.png
* sprites/{multiple}.svg
* sprites/{multiple}.svg.gz
* sprites/{multiple}.svg.br
* fonts/{multiple}.woff
* fonts/{multiple}.woff2

How do I have to configure `size-limit` to have it analyze the size correctly?
I'm working on an application, not a library. Does that even work then?

**Comment by ai** [comment]
If you are using Size Limit for app, you should have config like:

```
  webpack: false,
  path: "dist/main.js"
  limit: "100 KB"
```

**Comment by thasmo** [comment]
@ai, thanks for the answer. Running `size-limit` prints this:
```sh
Package size: 5.11 KB
With all dependencies, minified and gzipped
```
This seems to be the gzipped file-size of `main.js` itself.
That probably means it does not include `vendor.js` and any other assets.

So, I guess, to get the desired size, I will have to configure `path` to include all files.

**Comment by ai** [comment]
Yeap. For app you should add files to `path` manually depends on your needs 👍😊

**Comment by thasmo** [comment]
Thanks for the help!
