### ISSUE TITLE
Any way to use `output.path` for `path` option from webpack config with `webpack: false`?

### ISSUE THREAD

**Issue by ilyazub** [ai/size-limit#45]
I have different output paths for different environments. Something like
```js
// webpack.config.js
const config = require('config');

module.exports = {
  output: config.path.dist
};
```

As far as I can see, there is no way to specify `path` for `size-limit` like that. Neither in `package.json` nor in `.size-limit`.

There is a way to use `size-limit`'s cli tool, but `limit` option has been deprecated.
```js
const { exec } = require('child_process');
const config = require('config');

// Dumb example
exec(`npm run size-limit -- --no-webpack 200KB  ${config.path.dist}/app.*.js`);
exec(`npm run size-limit -- --no-webpack 220KB  ${config.path.dist}/vendor.*.js`);
```

So. Any way to use `output.path` for `path` option from the webpack config with `webpack: false`?

**Comment by ai** [comment]
Hm. Use CLI for now. Give me few days to think about flexibility like this.

Maybe I should move all CLI logic to JS API. Maybe I should un-deprecate `limit` arguments.

**Comment by ai** [comment]
Seems like the best solution here is to un-deprecate limit in CLI :D. It will be the most flexible way.

**Comment by ai** [comment]
`--limit` argument was added in 0.17 release.
