### ISSUE TITLE
Using with generated bundle name

### ISSUE THREAD

**Issue by pgrekovich** [ai/size-limit#5]
How can I use size-limit if I have bundle name like `bundle.b42f2f4b487ca5efc1f4.js`?

**Comment by ai** [comment]
You can use old CLI:

```js
size-limit 100KB bundle.*.js
```

**Comment by pgrekovich** [comment]
Maybe I misunderstood something. But I tried this way:
```
$ size-limit 100KB dist/vendor.*.js
Can't resolve 'D:\projects\forks\arc\dist\vendor.*.js' in 'D:\projects\forks\arc' 
```
With npm scripts same issue

**Comment by ai** [comment]
Ouh, yeap Windows shell doesn't support `*`. I will add glob support on this Friday.

**Comment by pgrekovich** [comment]
Thank, you awesome!

**Comment by ai** [comment]
Done 5917eb61e87cf3b877be8f8eb1d8d126c9d6ba6e

**Comment by ai** [comment]
Released in 0.7.

**Comment by pgrekovich** [comment]
I did modify test in #6 , and i think it's don't work in windows. Will be good if someone on windows will test it.

**Comment by ai** [comment]
You need to specify glob patter in `package.json` in `sizeLimit` section as mentioned in docs https://github.com/ai/size-limit#usage

**Comment by pgrekovich** [comment]
Oh, ok, thanks
