### ISSUE TITLE
yarn errors out in node 4

### ISSUE THREAD

**Issue by probablyup** [ai/size-limit#57]
Due to engines being set to >= 6.11.5: https://github.com/ai/size-limit/blob/master/package.json#L59-L61

**Comment by ai** [comment]
@probablyup because Node.js 4 is not supported anymore. It was not my desition. Webpack 4 removed Node.js 4 support.

If you need to call Size Limit on Travis CI, you can solve it with: https://github.com/ai/browserslist/blob/master/.travis.yml#L8-L9

**Comment by probablyup** [comment]
Okay, thank you for the very fast response!
