### ISSUE TITLE
size difference on Windows / failing unit test

### ISSUE THREAD

**Issue by DanielRuf** [ai/size-limit#62]
https://ci.appveyor.com/project/ai/size-limit/build/1.0.198

It happened after the latest dependency updates.

See https://github.com/ai/size-limit/commit/ac939608a14e0bd1eac2f0c52222ccaf43297a9f

**Comment by ai** [comment]
Sure. Wait a second

**Comment by ai** [comment]
067d6bb

**Comment by ai** [comment]
Thanks for notice :)
