### ISSUE TITLE
`ignore` option breaks Webpack builds

### ISSUE THREAD

**Issue by jaydenseric** [ai/size-limit#68]
If you use the `ignore` option for a dependency that is imported in the file you are testing the size of, you get a Webpack build error like this:

<img width="605" alt="screen shot 2018-08-10 at 5 13 26 pm" src="https://user-images.githubusercontent.com/1754873/43943967-bcbb688c-9cc0-11e8-9f85-b0d0677da025.png">

Also, without using the `ignore` option, if your dependency is a peerDependency and devDependency, but not a dependency, the same error happens. I assume the buggy mechanism for the `ignore` option is being repurposed to exclude peerDependency sizes from the report?

**Comment by jaydenseric** [comment]
Maybe a better approach is using Webpack `externals` config option, with regex?

> Every dependency that matches the given regular expression will be excluded from the output bundles.
> — https://webpack.js.org/configuration/externals/#regex

Also, see [this comment](https://github.com/webpack/webpack/issues/2858#issuecomment-240338772).

**Comment by ai** [comment]
@jaydenseric hm. interesting idea. Can you try to fix `index.js` in your `node_modules/size-limit`?

If it will work, feel free to send PR.

**Comment by ai** [comment]
Released in 0.19.2
