### ISSUE TITLE
Use `main` field as default `path`

### ISSUE THREAD

**Issue by piranna** [ai/size-limit#70]
Instead of need to set the path where `size-limit` will start to process files, use the `package.json` file `main` field (if missing, it's default value `index.js`) as default value to be used. I think it can be a good sane default and don't require to config `size-limit`, or maybe also to install it globally and just do some checking in random modules without need to modify them to add the config entry...

**Comment by piranna** [comment]
It was my idea, but was not able to find the exact point where I should do it, that's why I opened the issue instead. If you could be able to point me to the place, I'll happily do the pull-request :-)

**Comment by ai** [comment]
1. You need to fix config validator https://github.com/ai/size-limit/blob/master/cli.js#L105-L121
2. Somewhere here you need to set `entry.full` to `[resolve(packageJson.main)]` if `entry.path` is missed https://github.com/ai/size-limit/blob/master/cli.js#L246-L270
3. You need to update docs https://github.com/ai/size-limit/blob/master/README.md#config
4. Add `path`-less case here https://github.com/ai/size-limit/tree/master/test/fixtures and test it in https://github.com/ai/size-limit/blob/master/test/cli.test.js
5. Maybe update config validation tests

**Comment by ai** [comment]
If you don’t have time, I will find another developer to do it, it is not a problem (your idea is good, that is the main step here)

**Comment by piranna** [comment]
It's ok if any other wants to work on this :-)

**Comment by ai** [comment]
Done 326a890

**Comment by ai** [comment]
I will wait https://github.com/ai/size-limit/issues/71 before releasing it

**Comment by piranna** [comment]
Thank you! :-)
