### ISSUE TITLE
What about major release?

### ISSUE THREAD

**Issue by avdeev** [ai/size-limit#72]
Thank you for this util, it is very useful!

When do you plan to make major v1 release?

**Comment by ai** [comment]
I want to add source map support in `--why` for 1.0.

**Comment by avdeev** [comment]
@ai Thanks! Looking forward to the major! :)

Now it is not very convenient to update package. Every release i have to check the breaking changes. :(

**Comment by jaydenseric** [comment]
@ai is there any reason that feature could not be an enhancement for a v1.1 release?

I use `size-limit` for every one of my client-side packages, and frankly it's a terrible DX having to manually check the changelog for breaking changes, then type a new semver into `package.json` everytime there is a release:

<img width="254" alt="screen shot 2018-11-01 at 1 54 14 pm" src="https://user-images.githubusercontent.com/1754873/47829935-dec89b80-dddd-11e8-803e-5d73a20cf039.png">

This sort of friction causes people to put off updating the dependency.

**Comment by ai** [comment]
@jaydenseric the best way to do it, help me in finding `webpack-bundle-analyzer` replacement with source material support. It definitely are few options, we just need to check them out.

**Comment by avdeev** [comment]
🙌
