### ISSUE TITLE
Add support of dynamic output filename

### ISSUE THREAD

**Issue by liunaijia** [ai/size-limit#74]
For example, the following config will produce wrong size information.

```js
output: {
    path: path.resolve(__dirname, 'dist'),
    filename: '[name].js', // it's a dynamic filename
  },
```

Based on webpack document output filename could be a
- `[hash]`
The hash of the module identifier
- `[chunkhash]`
The hash of the chunk content
- `[name]`
The module name
- `[id]`
The module identifier
- `[query]`
The module query, i.e., the string following ? in the filename
- `[function]`
The function, which can return filename [string]

My `.size-limit.js` config:

```js
module.exports = [
  {
    path: "./src/index.jsx",
    config: "./webpack.config.js",
    limit: "500 KB",
  }
]
```

I know I can set `webpack: false` in size-limit config to calculate size based on the emitted files, but it would be great to build this feature into size-limit, I suppose it also paves the way for supporting multiple entry points.

**Comment by ai** [comment]
Sure. Do you have an idea how to implement it?

**Comment by liunaijia** [comment]
I guess `extractSize` function could read `state.toJson().entrypoints` which has entry points and their assets mapping information, and assets size could be parsed from `state.toJson().assets`.

```
"entrypoints": {
    "main": {
      "assets": [
        "runtime~main.js",
        "runtime~main.js.map",
        "vendors~main.js",
        "vendors~main.js.map",
        "main.js",
        "main.js.map"
      ],
      ...
    },
    "anotherentry": {
      "assets": [
        "runtime~anotherentry.js",
        "runtime~anotherentry.js.map",
        "anotherentry.js",
        "anotherentry.js.map"
      ],
      ...
    }
  },
```

**Comment by ai** [comment]
We can add `entry: 'main'` for this case.

Do you want to make PR to save your name in project history?

**Comment by ai** [comment]
> main is just a default name, it could be changed in webpack config.

Yeap, this is why we will have `entry` field in Size Limit config to allow user to change it according their Webpack config.

```
module.exports = [
  {
    entry: "main",
    config: "./webpack.config.js",
    limit: "500 KB",
  }
]
```
