### ISSUE TITLE
Support standard cosmiconfig file names

### ISSUE THREAD

**Issue by jaydenseric** [ai/size-limit#87]
At the moment `size-limit` does not support [standard cosmiconfig file names](https://github.com/davidtheclark/cosmiconfig#searchplaces):

https://github.com/ai/size-limit/blob/0.22.0/cli.js#L188

`.sizelimitrc.json` or `.size-limitrc.json`, or even `.size-limit.json` would be nicer than `.size-limit`, because editors could tell the file is JSON for syntax highlighting and Prettier formatting. Compare a `.size-limit` file opened next to a `.lintstagedrc.json` file in VS Code:

<img width="745" alt="Screen Shot 2019-03-31 at 2 58 18 pm" src="https://user-images.githubusercontent.com/1754873/55284617-fe341680-53c5-11e9-9bd9-b19e76c3624f.png">

I've recently changed my mind about including all config in `package.json` (as it bloats the published file). Of the ~6 config files I just created in a project for various tools `size-limit` was the only one I had to look up the documentation to work out the right filename.

Supporting standard cosmiconfig file names doesn't have to be a breaking change; `.size-limit`  could remain an option.

**Comment by ai** [comment]
Good idea. Let’s add `.size-limit.json` to config names and will promote it over `.size-limit` (I think we still should support `.size-limit` for compatibility).

**Comment by ai** [comment]
Done f997c12

**Comment by ai** [comment]
Done f997c12

**Comment by ai** [comment]
Released in 1.0

**Comment by jaydenseric** [comment]
Typo in the changelog entry (missing the leading`.`):

https://github.com/ai/size-limit/blob/master/CHANGELOG.md#10

**Comment by ai** [comment]
Fixed 684eb6a
