### ISSUE TITLE
Module parse failed

### ISSUE THREAD

**Issue by retyui** [ai/size-limit#92]
В мире react-native-* не существует прекрасный сборщик [metro](https://facebook.github.io/metro/) он примерно как parcel компилирует даже ваши node_modules
Некоторые модули в дальнейшем [реиспользуются](https://js.coach/?collection=React+Native&compatibility=Web) также для веб-платформы.

Как быть когда size-limit не понимает [flow.js](https://flow.org/) синтаксис?
```js
Module parse failed: Unexpected token (13:12)
You may need an appropriate loader to handle this file type.
| import { getCellStyle, getContainerStyle, styles } from './styles';
| 
> import type { Props, State } from './types';
```

**Comment by ai** [comment]
Для Flow надо использовать Size Limit после компилятора

https://github.com/ai/size-limit/blob/master/README.md#applications

**Comment by retyui** [comment]
Так проблема в том, что либы для react-native-* не компилируют!

**Comment by ai** [comment]
А что вы посылаете в браузер? Не Flow-же?

**Comment by retyui** [comment]
Бандлер изначально настроен что-бы компилировать весь javascript
и в пресатах есть плагины для flow.js

**Comment by ai** [comment]
То есть бандлер всё-таки есть? Кто-то генерирует JS который отправляется в браузер? Size Limit надо натравить именно на этот финальный JS-файл.

**Comment by retyui** [comment]
> То есть бандлер всё-таки есть?
Для модулей никаких бандлеров нету, весь код написан на современом ES2015+ плюс типы flow

Бандлер есть только в реальном проекте

**Comment by ai** [comment]
То есть у вас есть библиотека. Библиотека написана на Flow и в npm вы выкладываете flow-исходнии. Как вам тестировать размер библиотеки?

**Comment by retyui** [comment]
> То есть у вас есть библиотека. Библиотека написана на Flow и в npm вы выкладываете flow-исходнии.

Да, так и есть https://unpkg.com/react-native-fs@2.13.3/FS.common.js

> Как вам тестировать размер библиотеки?

Вырезать типы

**Comment by ai** [comment]
Честно скажу, что я не большой фанат выкладывать нестандартный синтаксис в npm.

Но если это точно надо, то есть пусть.

Вы можете содать кастомный вебпак-конфиг, где добавить лоадеры, который работает с Flow и указать конфиг в настройках Size Limit (опция `config`).
